import { useCallback, useEffect, useMemo, useState, type ReactNode } from 'react'
import { useNavigate } from 'react-router-dom'
import { formatCompactExpiry, formatExpiry, formatNumber, formatUsd, parseOrderNumber, parseStrikeList } from '../lib/formatters'
import { loadExplorerData, resolveAssetPrice, type ExplorerData, type ExplorerOrder } from '../lib/thetanuts'
import { buildPayoffCurve as buildVanillaCurve } from '../lib/payoff'
import { buildPayoffCurve as buildSpreadCurve } from '../lib/spreadPayoff'
import '../styles/discover.css'

export interface DiscoverPageProps { onConnectWallet?: () => void; onExplore?: () => void; onViewAll?: () => void }
const icons = { wallet: '▣', chart: '⌁', list: '▤', arrow: '›', shield: '♢', sparkle: '✳', rocket: '➤', bars: '▥', premium: '$', positions: '▣', orders: '☷', trend: '⌁', logo: '◇', eth: '♦', btc: '₿', sol: '≋' }
type MarketPrices = { ETH: number; BTC: number; SOL?: number }

export default function DiscoverPage({ onExplore, onViewAll }: DiscoverPageProps) {
  const navigate = useNavigate(); const [data, setData] = useState<ExplorerData | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [selectedOrderId, setSelectedOrderId] = useState<string | null>(null)
  const refresh = useCallback(async () => { setLoading(true); setError(null); try { setData(await loadExplorerData()) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Live market data is unavailable.') } finally { setLoading(false) } }, [])
  useEffect(() => { void refresh() }, [refresh])
  const orders = data?.orders ?? [], stats = data?.protocolStats?.stats, goToMarkets = onExplore ?? (() => navigate('/markets')), goToAnalyze = onViewAll ?? (() => navigate('/analyze'))
  return <main className="discover-page"><div className="discover-shell"><section className="discover-hero"><div className="hero-orbit" aria-hidden="true" /><div className="discover-copy"><div className="discover-eyebrow"><span>{icons.sparkle}</span> OPTIONS MADE CLEARER</div><h1>Crypto options<br />without the <em>headache.</em></h1><p>Explore live crypto markets, understand risk with clarity,<br className="desktop-break" /> and trade options with confidence.</p></div><div className="market-cards" aria-label="Live crypto market cards"><MarketCard asset="ETH" name="Ethereum" price={data?.marketData?.prices.ETH} lastUpdated={data?.marketData?.metadata.lastUpdated} loading={loading} /><MarketCard asset="BTC" name="Bitcoin" price={data?.marketData?.prices.BTC} lastUpdated={data?.marketData?.metadata.lastUpdated} loading={loading} /><MarketCard asset="SOL" name="Solana" price={data?.marketData?.prices.SOL} lastUpdated={data?.marketData?.metadata.lastUpdated} loading={loading} /></div></section>{error && <div className="discover-notice" role="alert">Unable to refresh the live dashboard: {error}</div>}<div className="discover-dashboard"><section className="discover-panel overview-panel"><PanelTitle icon={icons.chart} title="Market Overview" meta={<><span>All metrics are live</span><i /></>} /><div className="overview-grid"><Metric icon={icons.bars} tone="teal" label="Total OptionBook Volume" value={formatCompactUsd(stats?.totalVolumeUsd)} hint="Live protocol total" /><Metric icon={icons.premium} tone="violet" label="Total Premium" value={formatCompactUsd(stats?.totalPremiumUsd)} hint="Live protocol total" /><Metric icon={icons.positions} tone="blue" label="Tracked Positions" value={formatNumber(stats?.totalPositions)} hint={stats ? `${formatNumber(stats['24h'].positions)} in the last 24h` : 'Awaiting protocol data'} /><Metric icon={icons.orders} tone="amber" label="Live Orders" value={loading ? '…' : formatNumber(orders.length)} hint={orders.length ? 'Current OptionBook orders' : 'No orders currently available'} /></div></section><PayoffShowcase orders={orders} prices={data?.marketData?.prices} selectedOrderId={selectedOrderId} onViewAll={goToAnalyze} /><OrdersPreview orders={orders} loading={loading} selectedOrderId={selectedOrderId} onSelectOrder={setSelectedOrderId} onViewAll={goToMarkets} /><ExploreCTA onExplore={goToMarkets} /></div>{!!data?.errors.length && <p className="discover-source-note">Some live sources are currently unavailable; no synthetic market figures are shown.</p>}<footer className="discover-footer"><span>{icons.shield}</span> Built on <b>Base</b>. Secured by <strong>Thetanuts</strong>.</footer></div></main>
}
function MarketCard({ asset, name, price, lastUpdated, loading }: { asset: 'ETH' | 'BTC' | 'SOL'; name: string; price?: number; lastUpdated?: number; loading: boolean }) { const available = price !== undefined; return <article className={`market-card ${asset.toLowerCase()}`}><div className="market-card-head"><span className="coin">{icons[asset.toLowerCase() as 'eth' | 'btc' | 'sol']}</span><div><b>{asset}</b><small>{name}</small></div><span className="asset-glyph" aria-hidden="true">{icons[asset.toLowerCase() as 'eth' | 'btc' | 'sol']}</span></div><strong className="market-price">{loading ? 'Loading…' : available ? formatUsd(price) : 'Unavailable'}</strong><div className="market-sub">{available ? <><b>Live spot price</b>{formatMarketUpdate(lastUpdated) && <span>{formatMarketUpdate(lastUpdated)}</span>}</> : <span>Not available via Thetanuts</span>}</div><MarketHistoryPlaceholder available={available} /></article> }
function formatMarketUpdate(lastUpdated?: number): string | undefined { if (!lastUpdated) return undefined; const elapsedSeconds = Math.max(0, Math.floor((Date.now() - lastUpdated) / 1000)); return elapsedSeconds < 60 ? 'Updated just now' : `Updated ${Math.floor(elapsedSeconds / 60)}m ago` }
function MarketHistoryPlaceholder({ available }: { available: boolean }) { return <div className={`market-history-placeholder${available ? '' : ' muted'}`} aria-label={available ? 'Decorative background; historical chart data is not supplied by Thetanuts.' : 'Market price unavailable.'} /> }
function formatCompactUsd(value: number | string | undefined): string { if (value === undefined) return 'Unavailable'; const numericValue = Number(value); return Number.isFinite(numericValue) ? new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', notation: 'compact', minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(numericValue) : 'Unavailable' }
function PanelTitle({ icon, title, meta, action }: { icon: string; title: string; meta?: ReactNode; action?: () => void }) { return <div className="panel-title"><h2><span>{icon}</span>{title}</h2>{action ? <button type="button" onClick={action}>View all <b>{icons.arrow}</b></button> : <div className="panel-meta">{meta}</div>}</div> }
function Metric({ icon, tone, label, value, hint }: { icon: string; tone: string; label: string; value: string; hint: string }) { return <article className="overview-card"><span className={`metric-icon ${tone}`}>{icon}</span><small>{label}</small><strong>{value}</strong><em>{hint}</em></article> }
function PayoffShowcase({ orders, prices, selectedOrderId, onViewAll }: { orders: ExplorerOrder[]; prices: MarketPrices | undefined; selectedOrderId: string | null; onViewAll?: () => void }) { const validOrders = useMemo(() => orders.filter(order => order.optionType !== 'UNKNOWN' && parseStrikeList(order.strikes).length <= 2), [orders]); const order = validOrders.find(item => item.id === selectedOrderId) ?? validOrders[0]; const payoff = useMemo(() => { if (!order) return null; const strikes = parseStrikeList(order.strikes), premium = parseOrderNumber(order.pricePerContract), optionType = order.optionType === 'CALL' ? 'CALL' : 'PUT', spot = resolveAssetPrice(order.asset, prices) ?? strikes[0]; if (!spot || !strikes.length) return null; const breakeven = optionType === 'CALL' ? strikes[0] + premium : strikes[0] - premium, min = Math.max(0, Math.min(spot * .7, strikes[0] * .7, breakeven * .85)), max = Math.max(spot * 1.3, strikes[0] * 1.3, breakeven * 1.15), midpoint = (min + max) / 2, range = (max - min) / (min + max); const curve = strikes.length === 2 ? buildSpreadCurve({ spreadType: optionType === 'CALL' ? 'CALL_SPREAD' : 'PUT_SPREAD', nearStrike: strikes[0], farStrike: strikes[1], premium, positionSize: 1, currentPrice: midpoint }, range, 61) : buildVanillaCurve({ optionType, strike: strikes[0], premium, positionSize: 1, currentPrice: midpoint }, range, 61); const maxProfit = strikes.length === 2 ? Math.abs(strikes[1] - strikes[0]) - premium : optionType === 'PUT' ? Math.max(0, strikes[0] - premium) : undefined; return { curve, strike: strikes[0], breakeven, premium, maxLoss: premium, maxProfit } }, [order, prices]); const asset = order?.asset.toUpperCase().includes('BTC') ? 'BTC' : order?.asset.toUpperCase().includes('SOL') ? 'SOL' : 'ETH'; const assetIcon = asset === 'BTC' ? icons.btc : asset === 'SOL' ? icons.sol : icons.eth; return <section className="discover-panel payoff-panel"><PanelTitle icon={icons.trend} title="Payoff Showcase" action={onViewAll} /><div className="trade-caption"><span className={`tiny-asset ${asset.toLowerCase()}`}>{assetIcon} {asset}</span><b>{order ? parseStrikeList(order.strikes).length === 2 ? `${order.optionType === 'CALL' ? 'Bull Call' : 'Bear Put'} Spread` : `Long ${order.optionType === 'CALL' ? 'Call' : 'Put'}` : 'No live payoff available'}</b>{order && <small>Expiry: {formatExpiry(order.expiry)}</small>}</div>{payoff ? <PayoffGraph asset={asset} {...payoff} /> : <div className="payoff-empty">A valid live option order will appear here when available.</div>}</section> }
function PayoffGraph({ asset, curve, strike, breakeven, premium, maxLoss, maxProfit }: { asset: string; curve: { price: number; pnl: number }[]; strike: number; breakeven: number; premium: number; maxLoss: number; maxProfit?: number }) { const minX = curve[0].price, maxX = curve.at(-1)?.price ?? minX, values = curve.map(p => p.pnl), minY = Math.min(0, ...values), maxY = Math.max(0, ...values), scaleX = (n: number) => 42 + ((n - minX) / (maxX - minX || 1)) * 390, scaleY = (n: number) => 16 + (1 - (n - minY) / (maxY - minY || 1)) * 112, d = curve.map((p, i) => `${i ? 'L' : 'M'}${scaleX(p.price)},${scaleY(p.pnl)}`).join(' '), zero = scaleY(0), ticks = [maxY, (maxY + minY) / 2, minY], area = `${d} L${scaleX(maxX)},${zero} L${scaleX(minX)},${zero} Z`; return <><svg className="payoff-graph" viewBox="0 0 450 160" aria-label={`${asset} option net profit and loss at expiry`}><defs><clipPath id="profit-region"><rect x="42" y="16" width="390" height={Math.max(0, zero - 16)} /></clipPath><clipPath id="loss-region"><rect x="42" y={zero} width="390" height={Math.max(0, 128 - zero)} /></clipPath></defs><g className="graph-grid"><path d="M42 16H432M42 53H432M42 90H432M42 128H432M42 16V128M140 16V128M237 16V128M335 16V128M432 16V128" /></g><g className="graph-y-labels">{ticks.map((value, index) => <text key={index} x="2" y={scaleY(value) + 4}>{formatUsd(value, 0)}</text>)}</g><path className="profit-fill" clipPath="url(#profit-region)" d={area} /><path className="loss-fill" clipPath="url(#loss-region)" d={area} /><path className="payoff-line" d={d} /><path className="zero-line" d={`M42 ${zero}H432`} /><g className="graph-marker strike"><path d={`M${scaleX(strike)} 16V128`} /><text x={scaleX(strike)} y="12">Strike {formatUsd(strike, 0)}</text></g><g className="graph-marker breakeven"><path d={`M${scaleX(breakeven)} 16V128`} /><text x={scaleX(breakeven)} y="145">BE {formatUsd(breakeven, 0)}</text></g></svg><div className="graph-axis"><span>{formatUsd(minX, 0)}</span><span>{asset} Price at Expiry (USD)</span><span>{formatUsd(maxX, 0)}</span></div><div className="payoff-stats"><span>Premium <b>{formatUsd(premium)}</b></span><span>Max Loss <b>{formatUsd(maxLoss)}</b></span><span>Max Profit <b>{maxProfit === undefined ? 'Unlimited' : formatUsd(maxProfit)}</b></span></div></> }
function OrdersPreview({ orders, loading, selectedOrderId, onSelectOrder, onViewAll }: { orders: ExplorerOrder[]; loading: boolean; selectedOrderId: string | null; onSelectOrder: (id: string) => void; onViewAll?: () => void }) { const preview = orders.slice(0, 4); return <section className="discover-panel orders-panel"><PanelTitle icon={icons.list} title="Available Option Orders" action={onViewAll} />{loading ? <div className="orders-empty">Loading live OptionBook orders…</div> : !preview.length ? <div className="orders-empty">No live OptionBook orders available.</div> : <div className="orders-table-wrap"><table className="discover-orders"><thead><tr><th>Asset</th><th>Type</th><th>Strike</th><th>Expiry</th><th>Premium</th><th>Status</th></tr></thead><tbody>{preview.map(order => <tr key={order.id} className={selectedOrderId === order.id ? 'selected' : ''} onClick={() => onSelectOrder(order.id)} onKeyDown={event => { if (event.key === 'Enter' || event.key === ' ') onSelectOrder(order.id) }} tabIndex={0}><td><b className="order-asset">{order.asset}</b></td><td><span className={`order-type ${order.optionType.toLowerCase()}`}>{order.optionType === 'UNKNOWN' ? 'Order' : order.optionType[0] + order.optionType.slice(1).toLowerCase()}</span></td><td>{order.strikes}</td><td>{formatCompactExpiry(order.expiry)}</td><td>{formatNumber(order.pricePerContract, 4)}</td><td><span className="live-status">● Live</span></td></tr>)}</tbody></table></div>}</section> }
function ExploreCTA({ onExplore }: { onExplore?: () => void }) { return <section className="explore-cta"><div className="cta-orbits" aria-hidden="true"><span>{icons.rocket}</span></div><div><h2>Ready to explore?</h2><p>Dive into on-chain options markets<br />designed to be simple, transparent,<br />and powerful.</p><button type="button" onClick={onExplore}>Start Exploring <b>{icons.arrow}</b></button></div></section> }
