import { useReducer } from 'react'
import { useAccount } from '../context/AccountContext'
import PremiumUnlockModal from './PremiumUnlockModal'
import { NutIcon } from './VisualSystem'
import '../styles/strategy-overview-landing.css'

export type OverviewModal = 'about' | 'premium' | null
export type OverviewModalAction = { type: 'open'; modal: Exclude<OverviewModal, null> } | { type: 'close' }
export function overviewModalReducer(_: OverviewModal, action: OverviewModalAction): OverviewModal { return action.type === 'open' ? action.modal : null }
export function showsPremiumLink(tier: 'normal' | 'premium' | null): boolean { return tier !== 'premium' }

export default function SimpleStrategyOverview() {
  const { tier } = useAccount()
  const [modal, dispatch] = useReducer(overviewModalReducer, null)
  return <div className="simple-overview">
    <section className="strategy-card overview-about"><div><p className="eyebrow">GET STARTED</p><h2>What is Strategy Lab?</h2><p>Strategy Lab is a risk-free way to explore options strategies using real Thetanuts market data. You can practice with virtual USDC, save your ideas, and compare different strategies before trading with real funds.</p></div><div className="overview-features"><Feature icon="info" title="Learn" text="Understand how different options strategies work." /><Feature icon="board" title="Practice" text="Test ideas with virtual USDC and real market data." /><Feature icon="shield" title="Build Confidence" text="Compare strategies and understand how different market views affect their payoff." /></div></section>
    <div className="overview-content-grid"><section className="strategy-card overview-strategy-section"><header><h2>Options Strategies</h2><p>Explore the main strategy types available in Strategy Lab.</p></header><div className="overview-strategy-types"><StrategyType tone="bullish" icon="trend" title="Bullish Strategies" text="Strategies designed for a bullish market outlook." examples="Long Call · Bull Call Spread" /><StrategyType tone="neutral" icon="board" title="Neutral Strategies" text="Strategies designed for sideways or range-bound market views." examples="Iron Condor · Butterfly" /><StrategyType tone="bearish" icon="trend" title="Bearish Strategies" text="Strategies designed for a bearish market outlook." examples="Long Put · Bear Put Spread" /></div></section><aside className="strategy-card overview-account"><p className="eyebrow">YOUR ACCOUNT ACCESS</p><h2>{tier === 'premium' ? 'Premium' : 'Free'}</h2><p>{tier === 'premium' ? 'You have access to supported advanced options strategies and multi-leg strategy analysis.' : 'You currently have access to basic options strategies, including Call and Put analysis and paper trading.'}</p>{showsPremiumLink(tier) ? <><p>Advanced strategy structures such as spreads, butterflies, and condors require Premium.</p><button type="button" className="overview-text-action" onClick={() => dispatch({ type: 'open', modal: 'premium' })}>Learn about Premium →</button></> : <span className="overview-access-status">Premium Active</span>}</aside></div>
    <footer className="overview-info-strip"><NutIcon name="info" /><div><strong>Strategy Lab uses simulated trades with virtual USDC. No real funds are used in this environment.</strong><span>This environment is intended for strategy exploration and educational use.</span></div></footer>
    {modal === 'premium' && <PremiumUnlockModal onClose={() => dispatch({ type: 'close' })} />}
  </div>
}

export function OverviewHero() { const [modal, dispatch] = useReducer(overviewModalReducer, null); return <><div className="strategy-lab__intro overview-hero-copy"><p className="eyebrow">STRATEGY LAB</p><h1>Learn. Practice. Plan.<br /><em>Trade Smarter.</em></h1><p>Explore options strategies, test ideas with virtual USDC, and build confidence before trading with real funds.</p></div><div className="strategy-lab__art" aria-hidden="true"><i /><i /><i /></div><section className="strategy-lab__safety overview-why-card"><NutIcon name="spark" /><div><h2>Why use Strategy Lab?</h2><p>Practice different options strategies, understand how they perform in various market conditions, and find the approach that fits your risk profile — all with virtual funds.</p><button type="button" className="overview-text-action" onClick={() => dispatch({ type: 'open', modal: 'about' })}>Learn more →</button></div></section>{modal === 'about' && <AboutStrategyLabModal onClose={() => dispatch({ type: 'close' })} />}</> }

function AboutStrategyLabModal({ onClose }: { onClose: () => void }) { return <div className="modal-backdrop" role="presentation" onClick={onClose}><section className="modal-panel overview-about-modal" role="dialog" aria-modal="true" aria-labelledby="about-strategy-lab-title" onClick={(event) => event.stopPropagation()}><header><div><p className="eyebrow">STRATEGY LAB</p><h2 id="about-strategy-lab-title">About Strategy Lab</h2></div><button type="button" className="overview-modal-close" aria-label="Close About Strategy Lab" onClick={onClose}>×</button></header><p>Strategy Lab is a simulated environment for exploring options strategies before trading with real funds.</p><div className="overview-modal-sections"><ModalSection title="Paper Trading" text="Practice with virtual USDC using available Thetanuts market data." /><ModalSection title="Saved Strategies" text="Save strategy ideas so you can review them later." /><ModalSection title="Compare" text="Compare supported strategies side by side." /><ModalSection title="Premium Strategies" text="Advanced structures such as spreads, butterflies, and condors are available to Premium users where supported." /></div><footer><button type="button" className="modal-cancel" onClick={onClose}>Close</button></footer></section></div> }
function ModalSection({ title, text }: { title: string; text: string }) { return <section><h3>{title}</h3><p>{text}</p></section> }
function Feature({ icon, title, text }: { icon: 'info' | 'board' | 'shield'; title: string; text: string }) { return <article><NutIcon name={icon} /><div><strong>{title}</strong><p>{text}</p></div></article> }
function StrategyType({ tone, icon, title, text, examples }: { tone: string; icon: 'trend' | 'board'; title: string; text: string; examples: string }) { return <article className={tone}><NutIcon name={icon} /><h3>{title}</h3><p>{text}</p><span>{examples}</span></article> }
