import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { Line, LineChart, ReferenceLine, ResponsiveContainer, XAxis, YAxis } from 'recharts'
import { ContractRevertError, OrderExpiredError, ThetanutsError, type OrderWithSignature, type ThetanutsClient } from '@thetanuts-finance/thetanuts-client'
import { formatCompactExpiry, formatExpiry, formatNumber, formatUsd, parseOrderNumber, parseStrikeList } from './lib/formatters'
import { loadExplorerData, resolveAssetPrice, type ExplorerOrder } from './lib/thetanuts'
import { isPremiumUsdSafe } from './lib/orderPayoff'
import * as payoff from './lib/payoff'
import { isUserRejection, truncateAddress, useWallet } from './lib/WalletContext'
import { assertBaseNetwork, ensureTradeAllowance, validateTradePreflight, type FillPreview } from './lib/tradePreflight'
import type { BrowserProvider } from 'ethers'
import './styles/trade.css'

type Entry={id:string;order:OrderWithSignature}; export type Preview=FillPreview; type Phase='idle'|'approving'|'approved'|'signing'|'success'|'cancelled'|'error'
const unpack=(text:string):Entry[]=>JSON.parse(text,(_k,v)=>v&&typeof v==='object'&&'$bigint'in v?BigInt((v as {$bigint:string}).$bigint):v)
// The `amount` this returns is exactly what approve() and fill() below pass on to
// ensureAllowance()/fillOrder() — pulled out as a pure function (no React state)
// so "approval amount == fill amount, parsed from user input, never unbounded" is
// unit-testable without mounting the component.
export function computeFillPreview(client:ThetanutsClient,amountText:string,order:OrderWithSignature):Preview{return validateTradePreflight({client,amountText,order,walletConnected:true,baseNetwork:true})}
const describe=(e:unknown)=>e instanceof OrderExpiredError?'This live order has expired.':e instanceof ContractRevertError?'This live order is no longer available.':e instanceof ThetanutsError||e instanceof Error?e.message:'The transaction could not be completed.'
function watchBroadcast(provider:BrowserProvider,onBroadcast:()=>void){let pending:number|null=null;const listener=(value:unknown)=>{const info=value as {action?:string;payload?:unknown;result?:unknown};if(info.action==='sendRpcPayload'){const payloads=Array.isArray(info.payload)?info.payload:[info.payload];const item=(payloads as {id?:number;method?:string}[]).find(x=>x?.method==='eth_sendTransaction');if(item?.id!==undefined)pending=item.id}else if(info.action==='receiveRpcResult'&&pending!==null){const results=Array.isArray(info.result)?info.result:[info.result];const item=(results as {id?:number;error?:unknown}[]).find(x=>x?.id===pending);if(item&&!item.error){onBroadcast();pending=null}}};provider.on('debug',listener);return()=>provider.off('debug',listener)}

export default function FillFlow(){
 const [params]=useSearchParams(),id=params.get('order'),{connection,chain,client,connectWallet,switchToBase}=useWallet(); const [order,setOrder]=useState<ExplorerOrder|null>(null),[spot,setSpot]=useState<number|undefined>(),[loading,setLoading]=useState(!!id),[raw,setRaw]=useState<OrderWithSignature|null>(null),[stale,setStale]=useState(false),[amount,setAmount]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[phase,setPhase]=useState<Phase>('idle'),[message,setMessage]=useState<string|null>(null),[hash,setHash]=useState<string|null>(null),[walletRequired,setWalletRequired]=useState(false),[demoPreview,setDemoPreview]=useState(false),[readinessHint,setReadinessHint]=useState<string|null>(null)
 useEffect(()=>{if(!id)return;let live=true;void loadExplorerData().then(d=>{const found=d.orders?.find(x=>x.id===id)??null;if(live){setOrder(found);setSpot(found?resolveAssetPrice(found.asset,d.marketData?.prices):undefined);setStale(!found)}}).catch(()=>live&&setStale(true)).finally(()=>live&&setLoading(false));return()=>{live=false}},[id])
 const revalidate=useCallback(async()=>{if(!id)return null;try{const r=await fetch('/api/fill/orders');if(!r.ok)throw new Error('Unable to refresh this live order.');const found=unpack(await r.text()).find(x=>x.id===id)?.order??null;setRaw(found);setStale(!found);return found}catch(e){setMessage(e instanceof Error?e.message:'Unable to refresh this live order.');return null}},[id])
 useEffect(()=>{if(order)void revalidate()},[order,revalidate])
 const makePreview=useCallback((current?:OrderWithSignature|null)=>{const target=current??raw;try{const next=validateTradePreflight({client,amountText:amount,order:target,walletConnected:connection.status==='connected',baseNetwork:chain.status==='correct'});setPreview(next);setMessage(null);return next}catch(e){setPreview(null);setMessage(describe(e));return null}},[amount,chain.status,client,connection.status,raw])
 const review=useCallback(async()=>{const fresh=await revalidate();makePreview(fresh)},[makePreview,revalidate])
 useEffect(()=>{setPreview(null);setMessage(null);setPhase('idle')},[amount])
 const approve=useCallback(async()=>{const fresh=await revalidate(),value=makePreview(fresh);if(!fresh||!client||!value)return;setPhase('approving');try{await ensureTradeAllowance(client,value);setPhase('approved')}catch(e){setPhase(isUserRejection(e)?'cancelled':'error');setMessage(isUserRejection(e)?'Approval cancelled — no transaction was sent.':describe(e))}},[client,makePreview,revalidate])
 const fill=useCallback(async()=>{if(connection.status!=='connected'){setMessage('Connect your wallet before confirming this trade.');setPhase('error');return}if(chain.status!=='correct'||!client){setMessage('Switch your wallet to Base before confirming this trade.');setPhase('error');return}let stop=()=>{};try{await assertBaseNetwork(connection.provider);let fresh=await revalidate(),value=makePreview(fresh);if(!fresh||!value)throw new Error('This order could not be validated. Select another live order.');await ensureTradeAllowance(client,value);fresh=await revalidate();value=makePreview(fresh);if(!fresh||!value)throw new Error('This order changed before confirmation. Review the latest order and try again.');await assertBaseNetwork(connection.provider);await ensureTradeAllowance(client,value);setPhase('signing');stop=watchBroadcast(connection.provider,()=>setMessage('Transaction submitted. Confirming on Base…'));const receipt=await client.optionBook.fillOrder(fresh,value.amount);setHash(receipt.hash);setPhase('success')}catch(e){setPhase(isUserRejection(e)?'cancelled':'error');setMessage(isUserRejection(e)?'Trade cancelled — no transaction was sent.':describe(e))}finally{stop()}},[chain.status,client,connection,makePreview,revalidate])
 if(!id)return <Landing/>;if(loading)return <main className="trade-page"><div className="trade-shell trade-loading">Validating live OptionBook order…</div></main>;if(!order||stale)return <main className="trade-page"><div className="trade-shell"><section className="trade-empty"><span>⌁</span><h1>This live order is no longer available.</h1><p>Order terms are never revived from cached data. Browse the current OptionBook to select another live order.</p><Link to="/markets">Back to Markets →</Link></section></div></main>
 const strikes=parseStrikeList(order.strikes),safe=strikes.length===1&&order.optionType!=='UNKNOWN'&&isPremiumUsdSafe(order)&&spot!==undefined,premium=parseOrderNumber(order.pricePerContract);
 // Same parsing already used for every other numeric order field in this file (see OrderCard's
 // Datum rows) — availableAmount is a string on ExplorerOrder, never read with a raw Number().
 const maxAmount=parseOrderNumber(order.availableAmount)
 // Amount configuration needs a live signed order, but never a wallet or signer.
 // Keep it locked while approval/submission is in progress or after a completed fill.
 const nowSeconds=Math.floor(Date.now()/1000)
 const canEditAmount=!!raw&&!stale&&Number.isFinite(maxAmount)&&maxAmount>0
   &&order.optionType!=='UNKNOWN'&&strikes.length>0&&strikes.every(strike=>Number.isFinite(strike)&&strike>0)
   &&Number.isFinite(premium)&&premium>0&&raw.order.price>0n
   &&Number(raw.order.expiry)>nowSeconds
   &&(raw.rawApiData?.orderExpiryTimestamp===undefined||raw.rawApiData.orderExpiryTimestamp>nowSeconds)
   &&phase!=='approving'&&phase!=='signing'&&phase!=='success'
 // Same four conditions the primary button and Readiness already derive their state from — named
 // once here so the top Stepper, the button, and the checklist can never disagree with each other.
 const stage1Done=!!preview,stage2Done=connection.status==='connected',stage3Done=phase==='approved'||phase==='success',stage4Done=phase==='success';const stage=!stage1Done?1:!stage2Done?2:!stage3Done?3:!stage4Done?4:5
 const maxLossForAmount=safe&&preview&&client?payoff.maxLossTotal(premium,Number(client.utils.fromBigInt(preview.numContracts,6))):null
 // Lifted out of Summary so the new Token Approval card can show the same "Required for trade"
 // figure without a third copy of this exact bigint-formatting logic.
 const total=preview&&client?client.utils.fromBigInt(preview.totalCollateral,6):null
 const primary=connection.status==='no-wallet'?['Install MetaMask',()=>setWalletRequired(true)] as const:connection.status!=='connected'?[connection.status==='connecting'?'Connecting…':'Connect Wallet',()=>void connectWallet()] as const:chain.status!=='correct'?[chain.status==='switching'?'Switching…':'Switch to Base',()=>void switchToBase()] as const:!preview?['Review Fill',()=>void review()] as const:phase==='approved'?['Confirm Trade',()=>void fill()] as const:[phase==='approving'?'Confirm approval in wallet…':'Approve USDC',()=>void approve()] as const;const busy=phase==='approving'||phase==='signing'||connection.status==='connecting'||chain.status==='switching'
 return <main className="trade-page"><div className="trade-shell"><header className="trade-heading"><div className="trade-heading__copy"><span className="trade-section-kicker">OPTIONBOOK EXECUTION</span><h1>Trade</h1><p>Execute a live Thetanuts OptionBook order on Base.</p><div className="trade-badges"><span>● Live on Base</span><span>◈ Non-custodial · Secure · Transparent</span></div></div><Link className="trade-heading__link" to={`/analyze?order=${encodeURIComponent(order.id)}`}>View Full Analysis ↗</Link></header><Stepper stage={stage}/><div className="trade-grid"><section className="trade-left"><OrderCard order={order} spot={spot}/><AmountSize amount={amount} setAmount={setAmount} maxAmount={maxAmount} disabled={!canEditAmount} order={order} total={total}/><div className="trade-flow-row"><WalletNetworkCard connectWallet={connectWallet} switchToBase={switchToBase} onMissingWallet={()=>setWalletRequired(true)}/><TokenApprovalCard phase={phase} total={total} busy={busy} walletConnected={connection.status==='connected'} baseNetwork={chain.status==='correct'} onApprove={()=>void approve()}/><ReadyToFillCard connected={stage2Done} approved={stage3Done} reviewed={stage1Done} hint={readinessHint} onAction={()=>setReadinessHint(stage2Done&&stage3Done&&stage1Done?'Use the live execution CTA in the sidebar to confirm this fill.':'Complete wallet connection and token approval first.')}/></div><p className="trade-security">♧ Your funds never leave your wallet. Powered by Thetanuts on Base.</p></section><aside className="trade-sidebar"><div className="trade-live-status"><span className="trade-live-status__dot" aria-hidden="true"/><div><strong>Live order data</strong><small>Revalidated before review and fill.</small></div></div><section className="trade-preview"><header><div><span className="trade-section-kicker">EXECUTION</span><strong>Execution Summary</strong></div><span>Base</span></header>{phase==='success'&&hash?<Success order={order} hash={hash}/>:<><Summary order={order} preview={preview} client={client} total={total} maxLossForAmount={maxLossForAmount} amount={amount}/><RiskNotice/><button className="trade-primary" disabled={busy||(!!client&&!amount)} onClick={primary[1]}>{phase==='signing'?'Confirm in wallet…':primary[0]} <b>›</b></button>{message&&<p className={phase==='error'?'trade-error':'trade-note'}>{message}</p>}<small className="trade-foot">♧ Secure, on-chain execution via <b>Thetanuts</b> OptionBook.</small></>}</section></aside></div></div>{walletRequired&&<WalletRequiredPanel onClose={()=>setWalletRequired(false)} onInstall={()=>window.open('https://metamask.io','_blank','noreferrer')} onPreview={()=>{setWalletRequired(false);setDemoPreview(true)}}/>}{demoPreview&&<DemoPreview onClose={()=>setDemoPreview(false)}/>}</main>
}
function WalletRequiredPanel({onClose,onInstall,onPreview}:{onClose:()=>void;onInstall:()=>void;onPreview:()=>void}){return <div className="trade-interaction-backdrop" role="presentation" onMouseDown={onClose}><section className="trade-interaction-panel" role="dialog" aria-modal="true" aria-labelledby="trade-wallet-required-heading" onMouseDown={event=>event.stopPropagation()}><button type="button" className="trade-interaction-close" onClick={onClose} aria-label="Close wallet information">×</button><span className="trade-section-kicker">WALLET REQUIRED</span><h2 id="trade-wallet-required-heading">MetaMask is required for live execution on Base.</h2><p>Connect a wallet to approve the required collateral and fill this selected order.</p><div className="trade-interaction-actions"><button type="button" onClick={onInstall}>Install MetaMask</button><button type="button" className="secondary" onClick={onPreview}>Preview Trade Flow</button></div></section></div>}
function DemoPreview({onClose}:{onClose:()=>void}){return <div className="trade-interaction-backdrop" role="presentation" onMouseDown={onClose}><section className="trade-interaction-panel trade-demo-panel" role="dialog" aria-modal="true" aria-labelledby="trade-demo-heading" onMouseDown={event=>event.stopPropagation()}><header className="trade-interaction-panel__header"><div><span className="trade-section-kicker">NON-TRANSACTIONAL DEMO</span><h2 id="trade-demo-heading">Preview Trade Flow</h2></div><button type="button" className="trade-interaction-close" onClick={onClose} aria-label="Close trade preview">×</button></header><p className="trade-demo-disclaimer">Demo preview only — no transaction will be sent.</p><ol className="trade-demo-steps"><li className="trade-demo-step--available"><span>1</span><div><strong>Review Order</strong><small>Available · inspect the selected order.</small></div></li><li className="trade-demo-step--required"><span>2</span><div><strong>Connect Wallet</strong><small>Requires wallet · MetaMask is not installed.</small></div></li><li className="trade-demo-step--required"><span>3</span><div><strong>Approve Token</strong><small>Requires approval · no token request is made in preview.</small></div></li><li className="trade-demo-step--waiting"><span>4</span><div><strong>Fill on Base</strong><small>Waiting · live confirmation stays unavailable.</small></div></li></ol><p className="trade-demo-safety">This preview does not create a signer, change wallet state, approve tokens, or submit a transaction.</p><button type="button" className="trade-interaction-secondary" onClick={onClose}>Close Preview</button></section></div>}
function Landing(){return <main className="trade-page"><div className="trade-shell"><section className="trade-landing"><div className="trade-landing-hero"><div><p className="trade-kicker">OPTIONBOOK EXECUTION</p><h1>Trade</h1><p>Execute a live Thetanuts OptionBook order on Base.</p></div></div><div className="trade-landing-copy"><h2>You haven't selected an order yet.</h2><p>Choose a live order and review its risk before continuing to execution.</p></div><div className="trade-landing-actions"><Link to="/markets">Browse Live Markets →</Link><Link className="secondary" to="/analyze">Go to Analyze</Link></div><section className="trade-process" aria-labelledby="trade-process-heading"><div className="trade-process__heading"><div><p className="trade-process__kicker">HOW TRADING WORKS</p><h3 id="trade-process-heading">From selection to a confirmed fill</h3></div><small>Four simple steps</small></div><ol className="trade-process__steps"><li><span aria-hidden="true">1</span><div><strong>Select Order</strong><small>Choose a live OptionBook order.</small></div></li><li><span aria-hidden="true">2</span><div><strong>Analyze Risk</strong><small>Review payoff, breakeven and expiry outcome.</small></div></li><li><span aria-hidden="true">3</span><div><strong>Connect &amp; Approve</strong><small>Connect wallet on Base and approve required collateral if needed.</small></div></li><li><span aria-hidden="true">4</span><div><strong>Fill on Base</strong><small>Review the final amount and confirm in the wallet.</small></div></li></ol></section></section></div></main>}
function Datum({label,value}:{label:string;value:string}){return <div><dt>{label}</dt><dd>{value}</dd></div>}
function OrderCard({order,spot}:{order:ExplorerOrder;spot?:number}){return <section className="trade-card selected-order"><header><div><span className="trade-section-kicker">ORDER CONTEXT</span><h2>Selected Order</h2></div><div className="trade-order-actions"><span className={order.optionType.toLowerCase()}>{order.optionType}</span><Link to={`/analyze?order=${encodeURIComponent(order.id)}`}>View Analysis ↗</Link></div></header><div className="trade-asset"><i>{order.asset.slice(0,1)}</i><div><b>{order.asset}</b><small>{order.optionType==='UNKNOWN'?'Multi-leg order':`${order.optionType[0]+order.optionType.slice(1).toLowerCase()} option`}</small></div></div><dl className="trade-order-facts"><Datum label={order.strikes.includes('/')?'Strikes':'Strike'} value={order.strikes}/><Datum label="Expiry (DTE)" value={formatCompactExpiry(order.expiry)}/><Datum label="Premium" value={`${formatNumber(order.pricePerContract,6)} ${order.collateral}`}/><Datum label="Available size" value={`${formatNumber(order.availableAmount,4)} ${order.collateral}`}/><Datum label="Live spot" value={formatUsd(spot)}/><Datum label="Order ID" value={`${order.id.slice(0,12)}…`}/></dl></section>}
function Payoff({order,strike,premium,spot,safe}:{order:ExplorerOrder;strike?:number;premium:number;spot?:number;safe:boolean}){const data=useMemo(()=>safe?payoff.buildPayoffCurve({optionType:order.optionType as 'CALL'|'PUT',strike:strike!,premium,positionSize:1,currentPrice:spot!},.22,40):[],[safe,order.optionType,strike,premium,spot]);if(!safe)return <section className="trade-card trade-payoff unavailable"><h2>Payoff Preview</h2><p>Detailed payoff preview unavailable for this multi-leg order or because its premium cannot be safely compared in USD.</p><Link to={`/analyze?order=${encodeURIComponent(order.id)}`}>View order details →</Link></section>;const breakeven=payoff.breakevenPrice(order.optionType as 'CALL'|'PUT',strike!,premium);return <section className="trade-card trade-payoff"><header><h2>Payoff Preview at Expiry</h2><Link to={`/analyze?order=${encodeURIComponent(order.id)}`}>View Full Analysis ↗</Link></header><div className="trade-chart"><ResponsiveContainer width="100%" height={175}><LineChart data={data}><XAxis dataKey="price" tickFormatter={v=>formatUsd(v,0)} tick={{fill:'#8293a9',fontSize:10}}/><YAxis tickFormatter={v=>formatUsd(v,0)} tick={{fill:'#8293a9',fontSize:10}} width={55}/><ReferenceLine y={0} stroke="#62738b"/><ReferenceLine x={strike} stroke="#ff5f95" strokeDasharray="4 3"/><Line dataKey="pnl" stroke="#21d9bd" strokeWidth={2.5} dot={false}/></LineChart></ResponsiveContainer></div><div className="payoff-stats"><span>Break-even <b>{formatUsd(breakeven)}</b></span><span>Max loss <b>{formatNumber(premium,6)} USDC</b></span><span>Potential upside <b>{order.optionType==='CALL'?'Unlimited':formatUsd(Math.max(0,strike!-premium))}</b></span></div></section>}
// Lives in trade-left (not the sidebar) per the reference layout. Bound to the exact same
// amount/setAmount state as before — this is a relocation of the existing input+slider+Max block,
// not a new source of truth.
function AmountSize({amount,setAmount,maxAmount,disabled,order,total}:{amount:string;setAmount:(value:string)=>void;maxAmount:number;disabled:boolean;order:ExplorerOrder;total:string|null}){
 // Purely derived from the same amount/maxAmount already used by the input and slider above -
 // no new state, and clamped to [0,100] since the plain number input (unlike the range input) has
 // no hard max, so a manually-typed amount past availableAmount shouldn't display over 100%.
 const percentage=maxAmount>0?Math.min(100,Math.max(0,(Number(amount||0)/maxAmount)*100)):0
 return <section className="trade-card trade-amount-card"><h2>Amount &amp; Size</h2><p className="trade-amount-card__intro">Choose how much size you want to fill.</p><div className="trade-amount-columns"><div><label>Fill amount (USDC)<small>USDC</small></label><input type="number" inputMode="decimal" min="0" step="0.01" placeholder="0.00" value={amount} disabled={disabled} onChange={e=>setAmount(e.target.value)}/><div className="trade-amount-slider"><input type="range" min="0" max={maxAmount} step="0.01" value={amount||'0'} disabled={disabled} onChange={e=>setAmount(e.target.value)}/><button type="button" className="trade-amount-max-btn" disabled={disabled} onClick={()=>setAmount(String(maxAmount))}>Max</button></div><div className="trade-amount-marks"><span>0%</span><span>25%</span><span>50%</span><span>75%</span><span>100%</span></div><dl className="trade-amount-readouts"><Datum label="Available size" value={`${formatNumber(maxAmount,4)} USDC`}/><Datum label="Percentage of size" value={`${formatNumber(percentage,0)}%`}/></dl></div><div className="trade-estimated-cost"><h3>Estimated cost <span title="Total cost once a live preview is available.">ⓘ</span></h3>{total?<p className="trade-estimated-cost__total">{total} <b>USDC</b></p>:<p className="trade-estimated-cost__total trade-estimated-cost__total--empty">Review the order to see a live estimate</p>}<small>Based on the current fill preview</small><dl><Datum label="Unit premium" value={`${formatNumber(order.pricePerContract,6)} ${order.collateral} per contract`}/></dl></div></div><PartialFillNotice/><p className="trade-amount-card__hint">Preview determines the exact contracts and collateral under live protocol rules.</p></section>}
// Confirmed real, not assumed: tradePreflight.ts's validateTradePreflight lets any amount up to
// the order's max contracts through, and its own "exceeds availability" error explicitly offers a
// smaller amount rather than requiring the full available size - this is genuine partial-fill
// support, not a UI claim without backing logic.
function PartialFillNotice(){return <div className="trade-partial-notice"><span>ℹ</span><div><b>Partial fills supported</b><p>You can fill part of the available size. Unfilled size remains in the market.</p></div></div>}
// Pure presentational — stage is computed once in FillFlow from the same booleans Readiness and
// the primary button already use, and passed down. Steps before `stage` render complete, the step
// at `stage` renders active; a `stage` of 5 (one past the last) means every stage is done, so all
// four render complete with none highlighted as "current" — the state right after a successful fill.
function Stepper({stage}:{stage:number}){const labels=['Review Order','Connect Wallet','Approve Token','Fill on Base'];return <nav className="trade-stepper" aria-label="Trade progress">{labels.map((label,i)=>{const step=i+1,done=step<stage,active=step===stage;return <div key={label} className={`trade-stepper__step${done?' complete':active?' active':''}`}><i>{done?'✓':step}</i><span>{label}</span></div>})}</nav>}
function Summary({order,preview,client,total,maxLossForAmount,amount}:{order:ExplorerOrder;preview:Preview|null;client:ReturnType<typeof useWallet>['client'];total:string|null;maxLossForAmount:number|null;amount:string}){const contracts=preview&&client?client.utils.fromBigInt(preview.numContracts,6):null;return <section className="trade-summary"><div className="trade-summary-heading"><div><span className="trade-section-kicker">ORDER DETAILS</span><h2>Order Summary</h2></div><span className="trade-summary-status">Base</span></div><p>{order.asset} {order.strikes} {order.optionType==='UNKNOWN'?'Order':order.optionType}</p><small>Expiry: {formatExpiry(order.expiry)}</small><dl><Datum label="Premium (unit)" value={`${formatNumber(order.pricePerContract,6)} ${order.collateral}`}/><Datum label="Fill amount" value={amount?`${amount} USDC`:'Not selected'}/><Datum label="Available amount" value={`${formatNumber(order.availableAmount,4)} ${order.collateral}`}/>{contracts&&<Datum label="Contracts (preview)" value={contracts}/>} {maxLossForAmount!==null&&<Datum label="Capital at risk" value={formatUsd(maxLossForAmount)}/>}</dl>{total&&<p className="trade-total-cost"><span>Preview collateral</span><b>{total} USDC</b></p>}</section>}
// Card 1 of the reference's three-card wallet/approval row. Calls useWallet() itself for the full
// discriminated connection/chain objects (address, etc.) rather than taking them as props, matching
// how the Wallet component this replaces already did it — connectWallet/switchToBase are passed in
// since FillFlow already holds those same stable callbacks from its own useWallet() call.
function WalletNetworkCard({connectWallet,switchToBase,onMissingWallet}:{connectWallet:()=>Promise<void>;switchToBase:()=>Promise<void>;onMissingWallet:()=>void}){const {connection,chain}=useWallet();return <div className="trade-flow-card"><header><span className="trade-flow-card__num">1</span><div><b>Wallet &amp; Network</b><small>Connect a wallet on Base to continue.</small></div></header><div className="trade-flow-card__status"><span>{connection.status==='connected'?'✓':'○'}</span><div><b>{connection.status==='connected'?`Wallet ${truncateAddress(connection.address)}`:connection.status==='no-wallet'?'MetaMask not found':'No wallet connected'}</b><small>{connection.status==='connected'?(chain.status==='correct'?'Connected to Base':'Switch to Base to continue'):connection.status==='no-wallet'?'Requires wallet · install MetaMask to continue':'Connect to Base to proceed'}</small></div></div>{connection.status!=='connected'?<button type="button" className="trade-flow-card__action" disabled={connection.status==='connecting'} onClick={connection.status==='no-wallet'?onMissingWallet:()=>void connectWallet()}>{connection.status==='connecting'?'Connecting…':'Connect Wallet'}</button>:chain.status!=='correct'?<button type="button" className="trade-flow-card__action" disabled={chain.status==='switching'} onClick={()=>void switchToBase()}>{chain.status==='switching'?'Switching…':'Switch to Base'}</button>:<div className="trade-flow-card__row"><span>Network</span><b>✓ Base</b></div>}</div>}
// Card 2. "Required for trade" shows the same lifted `total` Summary/AmountSize already use - never
// a live on-chain allowance reading, since nothing in this file reads the current USDC allowance
// today (only ensureTradeAllowance, which sets it) and adding that would mean touching
// tradePreflight.ts/WalletContext.tsx, out of scope here.
function TokenApprovalCard({phase,total,busy,walletConnected,baseNetwork,onApprove}:{phase:Phase;total:string|null;busy:boolean;walletConnected:boolean;baseNetwork:boolean;onApprove:()=>void}){const approved=phase==='approved'||phase==='success';const state=approved?'ready':!walletConnected||!baseNetwork||!total?'required':busy?'waiting':'available';const status=approved?'Ready':!walletConnected?'Requires wallet':!baseNetwork?'Requires Base':!total?'Requires approval':busy?'Waiting':'Available';const hint=approved?'Approval is ready for this fill.':!walletConnected?'Connect wallet and review the order first.':!baseNetwork?'Switch to Base before approving.':!total?'Review the order before approving.':busy?'Waiting for wallet confirmation…':'Approval is available when you are ready.';return <div className="trade-flow-card"><header><span className="trade-flow-card__num">2</span><div><b>Token Approval</b><small>Allowance required to spend USDC.</small></div></header><div className={`trade-flow-card__status trade-flow-card__status--${state}`}><span>{approved?'✓':busy?'…':'○'}</span><div><b>USDC Allowance</b><small>{status}</small></div></div><div className="trade-flow-card__row"><span>Required for trade</span><b>{total?`${total} USDC`:'Review order first'}</b></div><p className="trade-flow-card__hint">{hint}</p><button type="button" className="trade-flow-card__action" disabled={approved||busy||!total||!walletConnected||!baseNetwork} onClick={onApprove}>{phase==='approving'?'Confirm approval in wallet…':'Approve USDC'}</button></div>}
// Card 3. Reuses the existing Readiness checklist as-is (same three booleans) rather than
// duplicating its markup. Its feedback-only button explains what is still required; the one
// real trigger for the fill transaction stays the sidebar's primary button.
function ReadyToFillCard({connected,approved,reviewed,hint,onAction}:{connected:boolean;approved:boolean;reviewed:boolean;hint:string|null;onAction:()=>void}){const ready=connected&&approved&&reviewed;return <div className="trade-flow-card"><header><span className="trade-flow-card__num">3</span><div><b>Ready to Fill</b><small>{ready?'Ready for live execution in the sidebar.':'Complete the required steps to enable live execution.'}</small></div></header><Readiness connected={connected} approved={approved} reviewed={reviewed}/><button type="button" className="trade-flow-card__action trade-flow-card__action--feedback" aria-disabled={!ready} onClick={onAction}>Review &amp; Execute</button><p className="trade-flow-card__hint">{hint??(ready?'Use the live execution CTA in the sidebar to confirm this fill.':'Complete wallet connection and token approval first.')}</p></div>}
// Static, no state/props — purely a reminder shown near the CTA, every render, regardless of phase.
function RiskNotice(){return <div className="trade-risk-notice"><span>⚠</span><div><b>Review risk before you sign</b><p>Options can expire worthless. Only trade what you can afford to lose.</p></div></div>}
// Same three booleans that already gate the primary button's label/enabled state — no new logic,
// just a visible checklist form of what's already being computed in FillFlow.
function Readiness({connected,approved,reviewed}:{connected:boolean;approved:boolean;reviewed:boolean}){const items:[string,boolean][]=[['Wallet connected',connected],['USDC allowance approved',approved],['Order reviewed',reviewed]];return <ul className="trade-readiness">{items.map(([label,done])=><li key={label} className={done?'complete':''}><span>{done?'✓':'○'}</span>{label}</li>)}</ul>}
function Success({order,hash}:{order:ExplorerOrder;hash:string}){return <div className="trade-success"><i>✓</i><h2>Trade Confirmed</h2><p>{order.asset} order confirmed on Base.</p><dl><Datum label="Order" value={`${order.id.slice(0,16)}…`}/><Datum label="Transaction" value={`${hash.slice(0,12)}…`}/><Datum label="Network" value="Base"/></dl><a href={`https://basescan.org/tx/${hash}`} target="_blank" rel="noreferrer">View on Base explorer ↗</a><Link to="/portfolio">View Portfolio</Link><Link to="/markets">Back to Markets</Link></div>}
