import { useCallback, useEffect, useMemo, useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { Line, LineChart, ReferenceLine, ResponsiveContainer, XAxis, YAxis } from 'recharts'
import { ContractRevertError, OrderExpiredError, ThetanutsError, type OrderWithSignature } from '@thetanuts-finance/thetanuts-client'
import { formatCompactExpiry, formatExpiry, formatNumber, formatUsd, parseOrderNumber, parseStrikeList } from './lib/formatters'
import { loadExplorerData, resolveAssetPrice, type ExplorerOrder } from './lib/thetanuts'
import * as payoff from './lib/payoff'
import { isUserRejection, truncateAddress, useWallet } from './lib/WalletContext'
import type { BrowserProvider } from 'ethers'
import './styles/trade.css'

type Entry={id:string;order:OrderWithSignature}; type Preview={amount:bigint;numContracts:bigint;pricePerContract:bigint;totalCollateral:bigint;collateralToken:string}; type Phase='idle'|'approving'|'approved'|'signing'|'success'|'cancelled'|'error'
const unpack=(text:string):Entry[]=>JSON.parse(text,(_k,v)=>v&&typeof v==='object'&&'$bigint'in v?BigInt((v as {$bigint:string}).$bigint):v)
const describe=(e:unknown)=>e instanceof OrderExpiredError?'This live order has expired.':e instanceof ContractRevertError?'This live order is no longer available.':e instanceof ThetanutsError||e instanceof Error?e.message:'The transaction could not be completed.'
function watchBroadcast(provider:BrowserProvider,onBroadcast:()=>void){let pending:number|null=null;const listener=(value:unknown)=>{const info=value as {action?:string;payload?:unknown;result?:unknown};if(info.action==='sendRpcPayload'){const payloads=Array.isArray(info.payload)?info.payload:[info.payload];const item=(payloads as {id?:number;method?:string}[]).find(x=>x?.method==='eth_sendTransaction');if(item?.id!==undefined)pending=item.id}else if(info.action==='receiveRpcResult'&&pending!==null){const results=Array.isArray(info.result)?info.result:[info.result];const item=(results as {id?:number;error?:unknown}[]).find(x=>x?.id===pending);if(item&&!item.error){onBroadcast();pending=null}}};provider.on('debug',listener);return()=>provider.off('debug',listener)}

export default function FillFlow(){
 const [params]=useSearchParams(),id=params.get('order'),{connection,chain,client,connectWallet,switchToBase}=useWallet(); const [order,setOrder]=useState<ExplorerOrder|null>(null),[spot,setSpot]=useState<number|undefined>(),[loading,setLoading]=useState(!!id),[raw,setRaw]=useState<OrderWithSignature|null>(null),[stale,setStale]=useState(false),[amount,setAmount]=useState(''),[preview,setPreview]=useState<Preview|null>(null),[phase,setPhase]=useState<Phase>('idle'),[message,setMessage]=useState<string|null>(null),[hash,setHash]=useState<string|null>(null)
 useEffect(()=>{if(!id)return;let live=true;void loadExplorerData().then(d=>{const found=d.orders?.find(x=>x.id===id)??null;if(live){setOrder(found);setSpot(found?resolveAssetPrice(found.asset,d.marketData?.prices):undefined);setStale(!found)}}).catch(()=>live&&setStale(true)).finally(()=>live&&setLoading(false));return()=>{live=false}},[id])
 const revalidate=useCallback(async()=>{if(!id)return null;try{const r=await fetch('/api/fill/orders');if(!r.ok)throw new Error('Unable to refresh this live order.');const found=unpack(await r.text()).find(x=>x.id===id)?.order??null;setRaw(found);setStale(!found);return found}catch(e){setMessage(e instanceof Error?e.message:'Unable to refresh this live order.');return null}},[id])
 useEffect(()=>{if(order)void revalidate()},[order,revalidate])
 const makePreview=useCallback((current?:OrderWithSignature|null)=>{if(!client||!(current??raw))return null;try{const value=client.utils.toBigInt(amount||'0',client.chainConfig.tokens.USDC.decimals);if(value<=0n)throw new Error('Enter a USDC amount greater than 0.');const p=client.optionBook.previewFillOrder(current??raw!,value),next={amount:value,...p};setPreview(next);setMessage(null);return next}catch(e){setPreview(null);setMessage(e instanceof Error?e.message:'Unable to calculate this fill.');return null}},[amount,client,raw])
 useEffect(()=>{setPreview(null);setMessage(null);setPhase('idle')},[amount])
 const approve=useCallback(async()=>{const fresh=await revalidate(),value=makePreview(fresh);if(!fresh||!client||!value)return;const spender=client.chainConfig.contracts.optionBook;if(!spender){setMessage('OptionBook is not deployed on Base.');return}setPhase('approving');try{await client.erc20.ensureAllowance(client.chainConfig.tokens.USDC.address,spender,value.amount);setPhase('approved')}catch(e){setPhase(isUserRejection(e)?'cancelled':'error');setMessage(isUserRejection(e)?'Approval cancelled — no transaction was sent.':describe(e))}},[client,makePreview,revalidate])
 const fill=useCallback(async()=>{const fresh=await revalidate(),value=makePreview(fresh);if(!fresh||!client||!value||connection.status!=='connected')return;setPhase('signing');const stop=watchBroadcast(connection.provider,()=>setMessage('Transaction submitted. Confirming on Base…'));try{const receipt=await client.optionBook.fillOrder(fresh,value.amount);setHash(receipt.hash);setPhase('success')}catch(e){setPhase(isUserRejection(e)?'cancelled':'error');setMessage(isUserRejection(e)?'Trade cancelled — no transaction was sent.':describe(e))}finally{stop()}},[client,connection,makePreview,revalidate])
 if(!id)return <Landing/>;if(loading)return <main className="trade-page"><div className="trade-shell trade-loading">Validating live OptionBook order…</div></main>;if(!order||stale)return <main className="trade-page"><div className="trade-shell"><section className="trade-empty"><span>⌁</span><h1>This live order is no longer available.</h1><p>Order terms are never revived from cached data. Browse the current OptionBook to select another live order.</p><Link to="/markets">Back to Markets →</Link></section></div></main>
 const strikes=parseStrikeList(order.strikes),safe=strikes.length===1&&order.optionType!=='UNKNOWN'&&order.collateral==='USDC'&&spot!==undefined,premium=parseOrderNumber(order.pricePerContract);const primary=connection.status==='no-wallet'?['Install MetaMask',()=>window.open('https://metamask.io','_blank','noreferrer')] as const:connection.status!=='connected'?[connection.status==='connecting'?'Connecting…':'Connect Wallet',()=>void connectWallet()] as const:chain.status!=='correct'?[chain.status==='switching'?'Switching…':'Switch to Base',()=>void switchToBase()] as const:!preview?['Review Fill',()=>makePreview()] as const:phase==='approved'?['Confirm Trade',()=>void fill()] as const:[phase==='approving'?'Confirm approval in wallet…':'Approve USDC',()=>void approve()] as const;const busy=phase==='approving'||phase==='signing'||connection.status==='connecting'||chain.status==='switching'
 return <main className="trade-page"><div className="trade-shell"><header className="trade-heading"><div><h1>Trade</h1><p>Execute a live Thetanuts OptionBook order on Base.</p><div className="trade-badges"><span>● Live on Base</span><span>◈ Non-custodial · Secure · Transparent</span></div></div><Link to={`/analyze?order=${encodeURIComponent(order.id)}`}>View Full Analysis ↗</Link></header><div className="trade-grid"><section className="trade-left"><OrderCard order={order} spot={spot}/><Payoff order={order} strike={strikes[0]} premium={premium} spot={spot} safe={safe}/><Steps connected={connection.status==='connected'} correct={chain.status==='correct'} reviewed={!!preview} phase={phase}/><p className="trade-security">♧ Your funds never leave your wallet. Powered by Thetanuts on Base.</p></section><aside><section className="trade-preview"><header><strong>⌘ Trade Preview</strong><span>Base</span></header>{phase==='success'&&hash?<Success order={order} hash={hash}/>:<><Summary order={order} preview={preview} client={client}/><div className="trade-amount"><label>Amount to spend <small>USDC collateral</small></label><input type="number" inputMode="decimal" min="0" step="0.01" placeholder="0.00" value={amount} disabled={!client} onChange={e=>setAmount(e.target.value)}/><p>Preview determines the exact contracts and collateral under live protocol rules.</p></div><Wallet connection={connection.status} chain={chain.status}/><button className="trade-primary" disabled={busy||(!!client&&!amount)} onClick={primary[1]}>{phase==='signing'?'Confirm in wallet…':primary[0]} <b>›</b></button>{message&&<p className={phase==='error'?'trade-error':'trade-note'}>{message}</p>}<small className="trade-foot">♧ Secure, on-chain execution via <b>Thetanuts</b> OptionBook.</small></>}</section></aside></div></div></main>
}
function Landing(){return <main className="trade-page"><div className="trade-shell"><section className="trade-landing"><p className="trade-kicker">OPTIONBOOK EXECUTION</p><h1>Trade</h1><p>Execute a live Thetanuts OptionBook order on Base.</p><h2>You haven’t selected an order yet.</h2><div><Link to="/markets">Browse Live Markets →</Link><Link className="secondary" to="/analyze">Go to Analyze</Link></div><section><h3>How trading works</h3><ol><li>Select a live order</li><li>Review its risk in Analyze</li><li>Connect your wallet</li><li>Approve the required token if needed</li><li>Confirm the trade on Base</li></ol></section></section></div></main>}
function Datum({label,value}:{label:string;value:string}){return <div><dt>{label}</dt><dd>{value}</dd></div>}
function OrderCard({order,spot}:{order:ExplorerOrder;spot?:number}){return <section className="trade-card selected-order"><header><strong>▤ Selected Order</strong><span className={order.optionType.toLowerCase()}>{order.optionType}</span></header><div className="trade-asset"><i>{order.asset.slice(0,1)}</i><div><b>{order.asset}</b><small>{order.optionType==='UNKNOWN'?'Multi-leg order':`${order.optionType[0]+order.optionType.slice(1).toLowerCase()} option`}</small></div></div><dl><Datum label={order.strikes.includes('/')?'Strikes':'Strike'} value={order.strikes}/><Datum label="Expiry" value={formatCompactExpiry(order.expiry)}/><Datum label="Premium" value={`${formatNumber(order.pricePerContract,6)} ${order.collateral}`}/><Datum label="Available amount" value={formatNumber(order.availableAmount,4)}/><Datum label="Live spot" value={formatUsd(spot)}/><Datum label="Order ID" value={`${order.id.slice(0,12)}…`}/></dl></section>}
function Payoff({order,strike,premium,spot,safe}:{order:ExplorerOrder;strike?:number;premium:number;spot?:number;safe:boolean}){const data=useMemo(()=>safe?payoff.buildPayoffCurve({optionType:order.optionType as 'CALL'|'PUT',strike:strike!,premium,positionSize:1,currentPrice:spot!},.22,40):[],[safe,order.optionType,strike,premium,spot]);if(!safe)return <section className="trade-card trade-payoff unavailable"><h2>Payoff Preview</h2><p>Detailed payoff preview unavailable for this multi-leg order or because its premium cannot be safely compared in USD.</p><Link to={`/analyze?order=${encodeURIComponent(order.id)}`}>View order details →</Link></section>;const breakeven=payoff.breakevenPrice(order.optionType as 'CALL'|'PUT',strike!,premium);return <section className="trade-card trade-payoff"><header><h2>Payoff Preview at Expiry</h2><Link to={`/analyze?order=${encodeURIComponent(order.id)}`}>View Full Analysis ↗</Link></header><div className="trade-chart"><ResponsiveContainer width="100%" height={175}><LineChart data={data}><XAxis dataKey="price" tickFormatter={v=>formatUsd(v,0)} tick={{fill:'#8293a9',fontSize:10}}/><YAxis tickFormatter={v=>formatUsd(v,0)} tick={{fill:'#8293a9',fontSize:10}} width={55}/><ReferenceLine y={0} stroke="#62738b"/><ReferenceLine x={strike} stroke="#ff5f95" strokeDasharray="4 3"/><Line dataKey="pnl" stroke="#21d9bd" strokeWidth={2.5} dot={false}/></LineChart></ResponsiveContainer></div><div className="payoff-stats"><span>Break-even <b>{formatUsd(breakeven)}</b></span><span>Max loss <b>{formatNumber(premium,6)} USDC</b></span><span>Potential upside <b>{order.optionType==='CALL'?'Unlimited':formatUsd(Math.max(0,strike!-premium))}</b></span></div></section>}
function Steps({connected,correct,reviewed,phase}:{connected:boolean;correct:boolean;reviewed:boolean;phase:Phase}){const a:[string,boolean][]=[['Connect Wallet',connected],['Check Base Network',correct],['Approve USDC',phase==='approved'||phase==='success'],['Review Order',reviewed],['Confirm Trade',phase==='success']];return <section className="trade-card trade-steps"><h2>Fill Order: Step-by-Step</h2><div>{a.map(([label,done],i)=><article key={label} className={done?'complete':''}><i>{done?'✓':i+1}</i><b>{label}</b><small>{done?'Complete':'Pending'}</small></article>)}</div></section>}
function Summary({order,preview,client}:{order:ExplorerOrder;preview:Preview|null;client:ReturnType<typeof useWallet>['client']}){const contracts=preview&&client?client.utils.fromBigInt(preview.numContracts,6):null,total=preview&&client?client.utils.fromBigInt(preview.totalCollateral,6):null;return <section className="trade-summary"><h2>Order Summary</h2><p>{order.asset} {order.strikes} {order.optionType==='UNKNOWN'?'Order':order.optionType}</p><small>Expiry: {formatExpiry(order.expiry)}</small><dl><Datum label="Premium" value={`${formatNumber(order.pricePerContract,6)} ${order.collateral}`}/>{contracts&&<Datum label="Contracts (preview)" value={contracts}/>} {total&&<Datum label="Required collateral" value={`${total} USDC`}/>}</dl></section>}
function Wallet({connection,chain}:{connection:string;chain:string}){const {connection:w}=useWallet();return <div className="trade-wallet-state"><span>{connection==='connected'?'✓':'○'}</span><div><b>{connection==='connected'?`Wallet ${truncateAddress(w.status==='connected'?w.address:'')}`:connection==='no-wallet'?'MetaMask not found':'Wallet disconnected'}</b><small>{chain==='correct'?'Connected to Base':connection==='connected'?'Switch to Base before trading':'Connect to review and execute this order'}</small></div></div>}
function Success({order,hash}:{order:ExplorerOrder;hash:string}){return <div className="trade-success"><i>✓</i><h2>Trade Confirmed</h2><p>{order.asset} order confirmed on Base.</p><dl><Datum label="Order" value={`${order.id.slice(0,16)}…`}/><Datum label="Transaction" value={`${hash.slice(0,12)}…`}/><Datum label="Network" value="Base"/></dl><a href={`https://basescan.org/tx/${hash}`} target="_blank" rel="noreferrer">View on Base explorer ↗</a><Link to="/portfolio">View Portfolio</Link><Link to="/markets">Back to Markets</Link></div>}
