import { useCallback, useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { formatCompactExpiry, formatNumber, formatUsd, parseOrderNumber, parseStrikeList } from './lib/formatters'
import { loadExplorerData, type ExplorerData, type ExplorerOrder } from './lib/thetanuts'
import './styles/markets.css'
import './styles/markets-fixes.css'

type CardAsset = 'ETH' | 'BTC' | 'SOL'
type AssetFilter = 'ALL' | string
type TypeFilter = 'ALL' | 'CALL' | 'PUT' | 'SPREAD'
type OrderKind = Exclude<TypeFilter, 'ALL'> | 'UNKNOWN'
type SortOption = 'EXPIRY_ASC' | 'EXPIRY_DESC' | 'STRIKE_ASC' | 'STRIKE_DESC' | 'PREMIUM_ASC' | 'PREMIUM_DESC'
const PAGE_SIZE = 8
const assetNames: Record<CardAsset, string> = { ETH: 'Ethereum', BTC: 'Bitcoin', SOL: 'Solana' }

function orderAsset(order: ExplorerOrder): string { return order.asset.trim().toUpperCase() || 'UNKNOWN' }
function TokenIcon({ asset }: { asset: string }) { const name = asset.toUpperCase(); const shapes = name === 'ETH' ? <><path d="M12 2 6.5 12 12 15.2 17.5 12 12 2Z" /><path d="m12 16.5-5.5-3.2L12 22l5.5-8.7-5.5 3.2Z" opacity=".72" /></> : name === 'BTC' ? <><path d="M9 4.2h4.8c2.2 0 3.5 1 3.5 2.7 0 1.2-.7 2.1-1.7 2.5 1.5.3 2.5 1.4 2.5 3.1 0 2.2-1.8 3.5-4.6 3.5H9V4.2Zm3 2.2v2.1h1.5c.8 0 1.3-.4 1.3-1.1s-.5-1-1.3-1H12Zm0 4.2v2.8h1.9c1 0 1.6-.5 1.6-1.4s-.6-1.4-1.6-1.4H12Z" /><path d="M10.2 2v16M14.1 2v16" fill="none" stroke="currentColor" strokeWidth="1.1" /></> : name === 'SOL' ? <><path d="M6 5h12l-2.6 2.8H3.4L6 5Z" /><path d="M18 10.6H6L8.6 7.8h12L18 10.6Z" opacity=".78" /><path d="M6 16.2h12L15.4 19H3.4L6 16.2Z" /></> : name === 'AVAX' ? <><path d="M12 2.8 20 7.4v9.2L12 21.2 4 16.6V7.4l8-4.6Z" opacity=".35" /><path d="m12.1 6.1-4.3 8h3l1.3-2.4 1.4 2.4h3l-4.4-8ZM8.1 16h3.1l.9-1.7-1.5-2.5L8.1 16Z" /></> : name === 'BNB' ? <><path d="m12 3 3 3-3 3-3-3 3-3Zm-5 5 3 3-3 3-3-3 3-3Zm10 0 3 3-3 3-3-3 3-3Zm-5 5 3 3-3 3-3-3 3-3Z" /><path d="m12 8 4 4-4 4-4-4 4-4Z" opacity=".8" /></> : name === 'XRP' ? <><path d="M5 6.2h2.8l3.1 3.1c.6.6 1.6.6 2.2 0l3.1-3.1H19l-4.3 4.3a3.8 3.8 0 0 1-5.4 0L5 6.2Z" /><path d="M5 17.8h2.8l3.1-3.1c.6-.6 1.6-.6 2.2 0l3.1 3.1H19l-4.3-4.3a3.8 3.8 0 0 0-5.4 0L5 17.8Z" /></> : <circle cx="12" cy="12" r="6" />; return <svg className="token-icon" viewBox="0 0 24 24" aria-hidden="true" fill="currentColor">{shapes}</svg> }
function orderType(order: ExplorerOrder): OrderKind { return parseStrikeList(order.strikes).length > 1 ? 'SPREAD' : order.optionType }

export default function OptionsExplorer() {
  const navigate = useNavigate()
  const [data, setData] = useState<ExplorerData | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState<string | null>(null)
  const [assetFilter, setAssetFilter] = useState<AssetFilter>('ALL'), [typeFilter, setTypeFilter] = useState<TypeFilter>('ALL'), [expiryFilter, setExpiryFilter] = useState('ALL'), [sort, setSort] = useState<SortOption>('EXPIRY_ASC'), [page, setPage] = useState(1)
  const refresh = useCallback(async () => { setLoading(true); setError(null); try { setData(await loadExplorerData()) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Live market data is unavailable.') } finally { setLoading(false) } }, [])
  useEffect(() => { void refresh() }, [refresh])
  const orders = data?.orders ?? []
  const assets = useMemo(() => [...new Set(orders.map(orderAsset))].sort(), [orders])
  const hasSpreads = useMemo(() => orders.some(order => orderType(order) === 'SPREAD'), [orders])
  const expiries = useMemo(() => [...new Set(orders.map(order => order.expiry))].sort((a, b) => Number(a) - Number(b)), [orders])
  const filteredOrders = useMemo(() => orders.filter(order => assetFilter === 'ALL' || orderAsset(order) === assetFilter).filter(order => typeFilter === 'ALL' || orderType(order) === typeFilter).filter(order => expiryFilter === 'ALL' || order.expiry === expiryFilter).sort((a, b) => {
    const strike = parseOrderNumber(a.strikes) - parseOrderNumber(b.strikes), premium = parseOrderNumber(a.pricePerContract) - parseOrderNumber(b.pricePerContract), expiry = Number(a.expiry) - Number(b.expiry)
    const comparison = sort.startsWith('EXPIRY') ? expiry : sort.startsWith('STRIKE') ? strike : premium
    return sort.endsWith('DESC') ? -comparison : comparison
  }), [assetFilter, expiryFilter, orders, sort, typeFilter])
  useEffect(() => { setPage(1) }, [assetFilter, expiryFilter, sort, typeFilter])
  const totalPages = Math.max(1, Math.ceil(filteredOrders.length / PAGE_SIZE)), currentPage = Math.min(page, totalPages), paginatedOrders = filteredOrders.slice((currentPage - 1) * PAGE_SIZE, currentPage * PAGE_SIZE)
  const activity = useMemo(() => ({ total: orders.length, calls: orders.filter(order => orderType(order) === 'CALL').length, puts: orders.filter(order => orderType(order) === 'PUT').length, spreads: orders.filter(order => orderType(order) === 'SPREAD').length, nearestExpiry: expiries[0], byAsset: assets.map(asset => [asset, orders.filter(order => orderAsset(order) === asset).length] as const) }), [assets, expiries, orders])
  const clearFilters = () => { setAssetFilter('ALL'); setTypeFilter('ALL'); setExpiryFilter('ALL'); setSort('EXPIRY_ASC') }
  return <main className="markets-page"><div className="markets-shell"><section className="markets-top"><div className="markets-heading"><h1>Markets</h1><p>Explore live <b>Thetanuts</b> OptionBook markets on <b>Base</b>.</p></div><div className="markets-cards"><MarketCard asset="ETH" price={data?.marketData?.prices.ETH} loading={loading} /><MarketCard asset="BTC" price={data?.marketData?.prices.BTC} loading={loading} /><MarketCard asset="SOL" price={data?.marketData?.prices.SOL} loading={loading} /></div></section>{error && <div className="markets-notice" role="alert">Unable to refresh live market data: {error}</div>}<div className="markets-layout"><section className="markets-main"><Filters assets={assets} hasSpreads={hasSpreads} expiries={expiries} assetFilter={assetFilter} typeFilter={typeFilter} expiryFilter={expiryFilter} sort={sort} onAsset={setAssetFilter} onType={setTypeFilter} onExpiry={setExpiryFilter} onSort={setSort} onClear={clearFilters} /><OrdersTable loading={loading} orders={paginatedOrders} total={filteredOrders.length} page={currentPage} totalPages={totalPages} onPage={setPage} onAnalyze={order => navigate(`/analyze?order=${order.id}`)} /></section><ActivityRail activity={activity} /></div><footer className="markets-footer">Built on <b>Base</b>. Secured by <strong>Thetanuts</strong>.</footer></div></main>
}

function MarketCard({ asset, price, loading }: { asset: CardAsset; price?: number; loading: boolean }) { return <article className={`markets-card ${asset.toLowerCase()}`}><div className="markets-card-head"><span className="markets-coin"><TokenIcon asset={asset} /></span><div><b>{asset}</b><small>{assetNames[asset]}</small></div><span className="markets-token" aria-hidden="true"><TokenIcon asset={asset} /></span></div><strong>{loading ? 'Loading…' : formatUsd(price)}</strong><span className="markets-spot">{price === undefined && !loading ? 'Not available via Thetanuts' : 'Live spot price'}</span><div className="markets-decoration" aria-hidden="true" /></article> }
function Filters({ assets, hasSpreads, expiries, assetFilter, typeFilter, expiryFilter, sort, onAsset, onType, onExpiry, onSort, onClear }: { assets: string[]; hasSpreads: boolean; expiries: string[]; assetFilter: AssetFilter; typeFilter: TypeFilter; expiryFilter: string; sort: SortOption; onAsset: (value: AssetFilter) => void; onType: (value: TypeFilter) => void; onExpiry: (value: string) => void; onSort: (value: SortOption) => void; onClear: () => void }) { const typeOptions: TypeFilter[] = hasSpreads ? ['ALL', 'CALL', 'PUT', 'SPREAD'] : ['ALL', 'CALL', 'PUT']; return <section className="markets-filters"><AssetFilterControl assets={assets} value={assetFilter} onChange={onAsset} /><FilterChips label="Type" value={typeFilter} options={typeOptions} onChange={onType} /><label className="markets-select"><span>Expiry</span><select value={expiryFilter} onChange={event => onExpiry(event.target.value)}><option value="ALL">All expiries</option>{expiries.map(expiry => <option key={expiry} value={expiry}>{formatCompactExpiry(expiry)}</option>)}</select></label><label className="markets-select"><span>Sort by</span><select value={sort} onChange={event => onSort(event.target.value as SortOption)}><option value="EXPIRY_ASC">Expiry (soonest)</option><option value="EXPIRY_DESC">Expiry (latest)</option><option value="STRIKE_ASC">Strike (low to high)</option><option value="STRIKE_DESC">Strike (high to low)</option><option value="PREMIUM_ASC">Premium (low to high)</option><option value="PREMIUM_DESC">Premium (high to low)</option></select></label><button className="markets-clear" type="button" onClick={onClear}>Clear filters</button></section> }
function AssetFilterControl({ assets, value, onChange }: { assets: string[]; value: AssetFilter; onChange: (value: AssetFilter) => void }) { const [open, setOpen] = useState(false), primary = ['ETH', 'BTC', 'SOL'].filter(asset => assets.includes(asset)), additional = assets.filter(asset => !primary.includes(asset)), selectedAdditional = additional.includes(value) ? value : undefined; return <fieldset className="markets-chip-group markets-asset-filter"><legend>Asset</legend><div><button type="button" className={value === 'ALL' ? 'active' : ''} onClick={() => { onChange('ALL'); setOpen(false) }}>All</button>{primary.map(asset => <button type="button" key={asset} className={value === asset ? 'active' : ''} onClick={() => { onChange(asset); setOpen(false) }}><TokenIcon asset={asset} />{asset}</button>)}{!!additional.length && <div className="markets-more"><button type="button" className={selectedAdditional ? 'active' : ''} aria-expanded={open} onClick={() => setOpen(current => !current)}>{selectedAdditional ?? 'More'} <span>▾</span></button>{open && <div className="markets-more-menu">{additional.map(asset => <button key={asset} type="button" className={value === asset ? 'active' : ''} onClick={() => { onChange(asset); setOpen(false) }}><TokenIcon asset={asset} />{asset}</button>)}</div>}</div>}</div></fieldset> }
function FilterChips({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: never) => void }) { return <fieldset className="markets-chip-group"><legend>{label}</legend><div>{options.map(option => <button type="button" key={option} className={value === option ? 'active' : ''} onClick={() => onChange(option as never)}>{option === 'ALL' ? 'All' : option[0] + option.slice(1).toLowerCase()}</button>)}</div></fieldset> }
function OrdersTable({ loading, orders, total, page, totalPages, onPage, onAnalyze }: { loading: boolean; orders: ExplorerOrder[]; total: number; page: number; totalPages: number; onPage: (page: number) => void; onAnalyze: (order: ExplorerOrder) => void }) { const start = total ? (page - 1) * PAGE_SIZE + 1 : 0, end = Math.min(page * PAGE_SIZE, total); return <section className="markets-table-panel">{loading && !total ? <div className="markets-empty">Loading live OptionBook orders…</div> : !total ? <div className="markets-empty">No active orders match these filters.</div> : <><div className="markets-table-wrap"><table className="markets-table"><thead><tr><th>Asset</th><th>Type</th><th>Strike</th><th>Expiry</th><th>Premium</th><th>Available</th><th>Action</th></tr></thead><tbody>{orders.map(order => <OrderRow key={order.id} order={order} onAnalyze={onAnalyze} />)}</tbody></table></div><div className="markets-pagination"><span>Showing {start}–{end} of {total} orders</span><div><button type="button" disabled={page === 1} onClick={() => onPage(page - 1)}>‹</button>{Array.from({ length: totalPages }, (_, index) => index + 1).filter(number => number === 1 || number === totalPages || Math.abs(number - page) <= 1).map((number, index, visible) => <span key={number}>{index > 0 && visible[index - 1] !== number - 1 && <em>…</em>}<button type="button" className={number === page ? 'active' : ''} onClick={() => onPage(number)}>{number}</button></span>)}<button type="button" disabled={page === totalPages} onClick={() => onPage(page + 1)}>›</button></div></div></>}</section> }
function OrderRow({ order, onAnalyze }: { order: ExplorerOrder; onAnalyze: (order: ExplorerOrder) => void }) { const asset = orderAsset(order), type = orderType(order); return <tr onClick={() => onAnalyze(order)}><td><span className={`markets-row-asset ${asset.toLowerCase()}`}><i><TokenIcon asset={asset} /></i>{asset}</span></td><td><span className={`markets-type ${type.toLowerCase()}`}>{type === 'SPREAD' ? 'Spread' : type[0] + type.slice(1).toLowerCase()}</span></td><td>{order.strikes}</td><td>{formatCompactExpiry(order.expiry)}</td><td>{formatNumber(order.pricePerContract, 6)} <small>{order.collateral}</small></td><td>{formatNumber(order.availableAmount, 4)}</td><td><button type="button" onClick={event => { event.stopPropagation(); onAnalyze(order) }}>Analyze</button></td></tr> }
function ActivityRail({ activity }: { activity: { total: number; calls: number; puts: number; spreads: number; nearestExpiry?: string; byAsset: readonly (readonly [string, number])[] } }) { return <aside className="markets-activity"><section><header><h2>Market Activity</h2><span className="markets-live">● Live</span></header><ActivityRow label="Active orders" value={formatNumber(activity.total)} /><ActivityRow label="Calls" value={formatNumber(activity.calls)} /><ActivityRow label="Puts" value={formatNumber(activity.puts)} /><ActivityRow label="Spreads" value={formatNumber(activity.spreads)} /><ActivityRow label="Nearest expiry" value={activity.nearestExpiry ? formatCompactExpiry(activity.nearestExpiry) : 'Unavailable'} /></section><section><header><h2>Asset Breakdown</h2><span className="markets-rail-label">Live orders</span></header>{activity.byAsset.map(([asset, count]) => <div className="markets-breakdown" key={asset}><span className={asset.toLowerCase()}><i><TokenIcon asset={asset} /></i>{asset}</span><b>{formatNumber(count)}</b></div>)}</section></aside> }
function ActivityRow({ label, value }: { label: string; value: string }) { return <div className="markets-activity-row"><span>{label}</span><b>{value}</b></div> }
