import { useCallback, useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { daysToExpiry, formatCompactExpiry, formatNumber, formatUsd, parseOrderNumber, parseStrikeList } from './lib/formatters'
import { loadExplorerData, resolveAssetPrice, type ExplorerData, type ExplorerOrder } from './lib/thetanuts'
import './styles/markets.css'
import './styles/markets-fixes.css'

type AssetFilter = 'ALL' | string
type TypeFilter = 'ALL' | 'CALL' | 'PUT' | 'SPREAD'
type OrderKind = Exclude<TypeFilter, 'ALL'> | 'UNKNOWN'
type SortOption = 'EXPIRY_ASC' | 'EXPIRY_DESC' | 'STRIKE_ASC' | 'STRIKE_DESC' | 'PREMIUM_ASC' | 'PREMIUM_DESC'
type MarketOutlook = 'BULLISH' | 'NEUTRAL' | 'BEARISH'
type PremiumFilter = 'ANY' | 'LOW' | 'MEDIUM' | 'HIGH'
type SizeFilter = 'ANY' | 'SMALL' | 'MEDIUM' | 'LARGE'
const PAGE_SIZE = 8

function orderAsset(order: ExplorerOrder): string { return order.asset.trim().toUpperCase() || 'UNKNOWN' }
function TokenIcon({ asset }: { asset: string }) { const name = asset.toUpperCase(); const shapes = name === 'ETH' ? <><path d="M12 2 6.5 12 12 15.2 17.5 12 12 2Z" /><path d="m12 16.5-5.5-3.2L12 22l5.5-8.7-5.5 3.2Z" opacity=".72" /></> : name === 'BTC' ? <><path d="M9 4.2h4.8c2.2 0 3.5 1 3.5 2.7 0 1.2-.7 2.1-1.7 2.5 1.5.3 2.5 1.4 2.5 3.1 0 2.2-1.8 3.5-4.6 3.5H9V4.2Zm3 2.2v2.1h1.5c.8 0 1.3-.4 1.3-1.1s-.5-1-1.3-1H12Zm0 4.2v2.8h1.9c1 0 1.6-.5 1.6-1.4s-.6-1.4-1.6-1.4H12Z" /><path d="M10.2 2v16M14.1 2v16" fill="none" stroke="currentColor" strokeWidth="1.1" /></> : name === 'SOL' ? <><path d="M6 5h12l-2.6 2.8H3.4L6 5Z" /><path d="M18 10.6H6L8.6 7.8h12L18 10.6Z" opacity=".78" /><path d="M6 16.2h12L15.4 19H3.4L6 16.2Z" /></> : name === 'AVAX' ? <><path d="M12 2.8 20 7.4v9.2L12 21.2 4 16.6V7.4l8-4.6Z" opacity=".35" /><path d="m12.1 6.1-4.3 8h3l1.3-2.4 1.4 2.4h3l-4.4-8ZM8.1 16h3.1l.9-1.7-1.5-2.5L8.1 16Z" /></> : name === 'BNB' ? <><path d="m12 3 3 3-3 3-3-3 3-3Zm-5 5 3 3-3 3-3-3 3-3Zm10 0 3 3-3 3-3-3 3-3Zm-5 5 3 3-3 3-3-3 3-3Z" /><path d="m12 8 4 4-4 4-4-4 4-4Z" opacity=".8" /></> : name === 'XRP' ? <><path d="M5 6.2h2.8l3.1 3.1c.6.6 1.6.6 2.2 0l3.1-3.1H19l-4.3 4.3a3.8 3.8 0 0 1-5.4 0L5 6.2Z" /><path d="M5 17.8h2.8l3.1-3.1c.6-.6 1.6-.6 2.2 0l3.1 3.1H19l-4.3-4.3a3.8 3.8 0 0 0-5.4 0L5 17.8Z" /></> : <circle cx="12" cy="12" r="6" />; return <svg className="token-icon" viewBox="0 0 24 24" aria-hidden="true" fill="currentColor">{shapes}</svg> }
function orderType(order: ExplorerOrder): OrderKind { return parseStrikeList(order.strikes).length > 1 ? 'SPREAD' : order.optionType }

function rankSuggestions(orders: ExplorerOrder[], outlook: MarketOutlook, prices: NonNullable<ExplorerData['marketData']>['prices'] | undefined) {
  const premiums = orders.map(order => parseOrderNumber(order.pricePerContract)), sizes = orders.map(order => parseOrderNumber(order.availableAmount))
  const minPremium = Math.min(...premiums), maxPremium = Math.max(...premiums), minSize = Math.min(...sizes), maxSize = Math.max(...sizes)
  const normalize = (value: number, min: number, max: number, fallback: number) => max === min ? fallback : Math.max(0, Math.min(1, (value - min) / (max - min)))
  return orders.map(order => {
    const type = orderType(order), spot = resolveAssetPrice(orderAsset(order), prices), strike = parseStrikeList(order.strikes)[0], dte = daysToExpiry(order.expiry), relativeStrike = spot && strike ? strike / spot : undefined
    const typeMatch = outlook === 'BULLISH' ? type === 'CALL' : outlook === 'BEARISH' ? type === 'PUT' : type === 'SPREAD'
    const preferredStrike = outlook === 'BULLISH' ? 1.03 : outlook === 'BEARISH' ? .97 : 1
    const moneynessScore = relativeStrike === undefined ? 10 : 30 * Math.max(0, 1 - Math.abs(relativeStrike - preferredStrike) / .35)
    const dteScore = 20 * Math.max(0, 1 - Math.abs(dte - 14) / 45)
    const sizeScore = 10 * normalize(parseOrderNumber(order.availableAmount), minSize, maxSize, .5)
    const premiumScore = 10 * (1 - normalize(parseOrderNumber(order.pricePerContract), minPremium, maxPremium, .5))
    return { order, dte, score: Math.round(Math.max(0, Math.min(100, (typeMatch ? 30 : 0) + moneynessScore + dteScore + sizeScore + premiumScore))) }
  })
}

export default function OptionsExplorer() {
  const navigate = useNavigate()
  const [data, setData] = useState<ExplorerData | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState<string | null>(null)
  const [sessionTrend, setSessionTrend] = useState<number[]>([])
  const [outlook, setOutlook] = useState<MarketOutlook>('BULLISH'), [assetFilter, setAssetFilter] = useState<AssetFilter>('ALL'), [typeFilter, setTypeFilter] = useState<TypeFilter>('ALL'), [expiryFilter, setExpiryFilter] = useState('ALL'), [premiumFilter, setPremiumFilter] = useState<PremiumFilter>('ANY'), [sizeFilter, setSizeFilter] = useState<SizeFilter>('ANY'), [sort, setSort] = useState<SortOption>('EXPIRY_ASC'), [page, setPage] = useState(1)
  const refresh = useCallback(async () => { setLoading(true); setError(null); try { setData(await loadExplorerData()) } catch (reason) { setError(reason instanceof Error ? reason.message : 'Live market data is unavailable.') } finally { setLoading(false) } }, [])
  useEffect(() => { void refresh() }, [refresh])
  const orders = data?.orders ?? []
  useEffect(() => { if (data) setSessionTrend(current => [...current, orders.length].slice(-30)) }, [data, orders.length])
  const assets = useMemo(() => [...new Set(orders.map(orderAsset))].sort(), [orders])
  const hasSpreads = useMemo(() => orders.some(order => orderType(order) === 'SPREAD'), [orders])
  const expiries = useMemo(() => [...new Set(orders.map(order => order.expiry))].sort((a, b) => Number(a) - Number(b)), [orders])
  const filteredOrders = useMemo(() => orders.filter(order => assetFilter === 'ALL' || orderAsset(order) === assetFilter).filter(order => typeFilter === 'ALL' || orderType(order) === typeFilter).filter(order => expiryFilter === 'ALL' || order.expiry === expiryFilter).filter(order => { const premium = parseOrderNumber(order.pricePerContract); return premiumFilter === 'ANY' || premiumFilter === 'LOW' && premium <= 50 || premiumFilter === 'MEDIUM' && premium > 50 && premium <= 500 || premiumFilter === 'HIGH' && premium > 500 }).filter(order => { const size = parseOrderNumber(order.availableAmount); return sizeFilter === 'ANY' || sizeFilter === 'SMALL' && size < 1_000 || sizeFilter === 'MEDIUM' && size >= 1_000 && size < 10_000 || sizeFilter === 'LARGE' && size >= 10_000 }).sort((a, b) => {
    const strike = parseOrderNumber(a.strikes) - parseOrderNumber(b.strikes), premium = parseOrderNumber(a.pricePerContract) - parseOrderNumber(b.pricePerContract), expiry = Number(a.expiry) - Number(b.expiry)
    const comparison = sort.startsWith('EXPIRY') ? expiry : sort.startsWith('STRIKE') ? strike : premium
    return sort.endsWith('DESC') ? -comparison : comparison
  }), [assetFilter, expiryFilter, orders, premiumFilter, sizeFilter, sort, typeFilter])
  useEffect(() => { setPage(1) }, [assetFilter, expiryFilter, premiumFilter, sizeFilter, sort, typeFilter])
  const totalPages = Math.max(1, Math.ceil(filteredOrders.length / PAGE_SIZE)), currentPage = Math.min(page, totalPages), paginatedOrders = filteredOrders.slice((currentPage - 1) * PAGE_SIZE, currentPage * PAGE_SIZE)
  const activity = useMemo(() => ({ total: orders.length, calls: orders.filter(order => orderType(order) === 'CALL').length, puts: orders.filter(order => orderType(order) === 'PUT').length, spreads: orders.filter(order => orderType(order) === 'SPREAD').length, nearestExpiry: expiries[0], byAsset: assets.map(asset => [asset, orders.filter(order => orderAsset(order) === asset).length] as const) }), [assets, expiries, orders])
  const suggestions = useMemo(() => rankSuggestions(filteredOrders, outlook, data?.marketData?.prices).sort((a, b) => b.score - a.score || parseOrderNumber(b.order.availableAmount) - parseOrderNumber(a.order.availableAmount)), [data?.marketData?.prices, filteredOrders, outlook])
  const clearFilters = () => { setAssetFilter('ALL'); setTypeFilter('ALL'); setExpiryFilter('ALL'); setPremiumFilter('ANY'); setSizeFilter('ANY'); setSort('EXPIRY_ASC') }
  return <main className="markets-page"><div className="markets-shell"><MarketSummary data={data} loading={loading} orderCount={orders.length} sessionTrend={sessionTrend} />{error && <div className="markets-notice" role="alert">Unable to refresh live market data: {error}</div>}<Filters outlook={outlook} onOutlook={setOutlook} assets={assets} hasSpreads={hasSpreads} expiries={expiries} assetFilter={assetFilter} typeFilter={typeFilter} expiryFilter={expiryFilter} premiumFilter={premiumFilter} sizeFilter={sizeFilter} sort={sort} onAsset={setAssetFilter} onType={setTypeFilter} onExpiry={setExpiryFilter} onPremium={setPremiumFilter} onSize={setSizeFilter} onSort={setSort} onClear={clearFilters} /><div className="markets-layout"><section className="markets-main"><SuggestedOpportunities loading={loading} suggestions={suggestions} onAnalyze={order => navigate(`/analyze?order=${order.id}`)} /><OrdersTable loading={loading} orders={paginatedOrders} total={filteredOrders.length} page={currentPage} totalPages={totalPages} onPage={setPage} onAnalyze={order => navigate(`/analyze?order=${order.id}`)} /></section><ActivityRail activity={activity} onBrowseAnalyze={() => navigate('/analyze')} /></div><footer className="markets-footer">Built on <b>Base</b>. Secured by <strong>Thetanuts</strong>.</footer></div></main>
}

function MarketSummary({ data, loading, orderCount, sessionTrend }: { data: ExplorerData | null; loading: boolean; orderCount: number; sessionTrend: number[] }) { const stats = data?.protocolStats?.stats, sparkline = sessionTrend.length > 1 ? toSparklinePath(sessionTrend) : undefined, updatedAt = data?.fetchedAt ? new Date(data.fetchedAt).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' }) : undefined; return <section className="markets-summary"><div className="markets-summary-intro"><span className="markets-summary-mark" aria-hidden="true">◈</span><div><h1>Live Options Markets</h1><p>Browse live Thetanuts OptionBook opportunities across assets, expiries, and strategies.</p></div></div><div className="markets-summary-stats"><SummaryStat label="Live orders" value={loading ? 'Loading…' : formatNumber(orderCount)} /><SummaryStat label="Total volume" value={stats ? formatUsd(stats.totalVolumeUsd) : 'Unavailable'} /><SummaryStat label="Open positions" value={stats ? formatNumber(stats.totalPositions) : 'Unavailable'} /></div><div className="markets-sparkline" aria-label="Live session order-count trend">{sparkline ? <svg viewBox="0 0 160 42" role="img"><path d={sparkline} fill="none" stroke="currentColor" strokeWidth="2" /><path d="M2 38h156" stroke="currentColor" strokeOpacity=".15" /></svg> : <div className="markets-sparkline-empty">Collecting live data…</div>}<span>{updatedAt ? `Live · ${updatedAt}` : 'Live session trend'}</span></div></section> }
function toSparklinePath(values: number[]): string { const min = Math.min(...values), max = Math.max(...values), range = max - min || 1; return values.map((value, index) => `${index ? 'L' : 'M'}${2 + index * 156 / (values.length - 1)} ${35 - (value - min) / range * 27}`).join(' ') }
function SummaryStat({ label, value }: { label: string; value: string }) { return <div className="markets-summary-stat"><span>{label}</span><b>{value}</b></div> }
function Filters({ outlook, onOutlook, assets, hasSpreads, expiries, assetFilter, typeFilter, expiryFilter, premiumFilter, sizeFilter, sort, onAsset, onType, onExpiry, onPremium, onSize, onSort, onClear }: { outlook: MarketOutlook; onOutlook: (value: MarketOutlook) => void; assets: string[]; hasSpreads: boolean; expiries: string[]; assetFilter: AssetFilter; typeFilter: TypeFilter; expiryFilter: string; premiumFilter: PremiumFilter; sizeFilter: SizeFilter; sort: SortOption; onAsset: (value: AssetFilter) => void; onType: (value: TypeFilter) => void; onExpiry: (value: string) => void; onPremium: (value: PremiumFilter) => void; onSize: (value: SizeFilter) => void; onSort: (value: SortOption) => void; onClear: () => void }) { const typeOptions: TypeFilter[] = hasSpreads ? ['ALL', 'CALL', 'PUT', 'SPREAD'] : ['ALL', 'CALL', 'PUT']; return <section className="markets-filters"><FilterChips label="Market outlook" value={outlook} options={['BULLISH', 'NEUTRAL', 'BEARISH']} onChange={onOutlook} /><AssetFilterControl assets={assets} value={assetFilter} onChange={onAsset} /><FilterChips label="Type" value={typeFilter} options={typeOptions} onChange={onType} /><SelectFilter label="Expiry" value={expiryFilter} options={[['ALL', 'All expiries'], ...expiries.map(expiry => [expiry, formatCompactExpiry(expiry)])]} onChange={onExpiry} /><SelectFilter label="Premium (USDC)" value={premiumFilter} options={[['ANY', 'Any'], ['LOW', 'Low (≤ 50)'], ['MEDIUM', 'Medium (50–500)'], ['HIGH', 'High (> 500)']]} onChange={onPremium} /><SelectFilter label="Available size" value={sizeFilter} options={[['ANY', 'Any'], ['SMALL', 'Small (< 1,000)'], ['MEDIUM', 'Medium (1,000–10,000)'], ['LARGE', 'Large (≥ 10,000)']]} onChange={onSize} /><label className="markets-select"><span>Sort by</span><select value={sort} onChange={event => onSort(event.target.value as SortOption)}><option value="EXPIRY_ASC">Expiry (soonest)</option><option value="EXPIRY_DESC">Expiry (latest)</option><option value="STRIKE_ASC">Strike (low to high)</option><option value="STRIKE_DESC">Strike (high to low)</option><option value="PREMIUM_ASC">Premium (low to high)</option><option value="PREMIUM_DESC">Premium (high to low)</option></select></label><button className="markets-clear" type="button" onClick={onClear}>Clear filters</button></section> }
function SelectFilter({ label, value, options, onChange }: { label: string; value: string; options: string[][]; onChange: (value: never) => void }) { return <label className="markets-select"><span>{label}</span><select value={value} onChange={event => onChange(event.target.value as never)}>{options.map(([option, name]) => <option key={option} value={option}>{name}</option>)}</select></label> }
function AssetFilterControl({ assets, value, onChange }: { assets: string[]; value: AssetFilter; onChange: (value: AssetFilter) => void }) { const [open, setOpen] = useState(false), primary = ['ETH', 'BTC', 'SOL'].filter(asset => assets.includes(asset)), additional = assets.filter(asset => !primary.includes(asset)), selectedAdditional = additional.includes(value) ? value : undefined, options = ['ALL', ...primary, 'MORE'], selectedIndex = selectedAdditional ? options.length - 1 : Math.max(0, options.indexOf(value)); return <fieldset className="markets-chip-group markets-asset-filter"><legend>Asset</legend><div className="markets-segmented" style={{ '--segments': options.length, '--selected': selectedIndex } as React.CSSProperties}><span className="markets-segment-pill" aria-hidden="true" />{options.map(option => option === 'MORE' ? <div className="markets-more" key={option}><button type="button" className={selectedAdditional ? 'active' : ''} aria-expanded={open} onClick={() => setOpen(current => !current)}>{selectedAdditional ?? 'More'} <span>▾</span></button>{open && <div className="markets-more-menu">{additional.map(asset => <button key={asset} type="button" className={value === asset ? 'active' : ''} onClick={() => { onChange(asset); setOpen(false) }}><TokenIcon asset={asset} />{asset}</button>)}</div>}</div> : <button type="button" key={option} className={value === option ? 'active' : ''} onClick={() => { onChange(option); setOpen(false) }}>{option === 'ALL' ? 'All' : <><TokenIcon asset={option} />{option}</>}</button>)}</div></fieldset> }
function FilterChips({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: never) => void }) { const selectedIndex = Math.max(0, options.indexOf(value)); return <fieldset className="markets-chip-group"><legend>{label}</legend><div className="markets-segmented" style={{ '--segments': options.length, '--selected': selectedIndex } as React.CSSProperties}><span className="markets-segment-pill" aria-hidden="true" />{options.map(option => <button type="button" key={option} className={value === option ? 'active' : ''} onClick={() => onChange(option as never)}>{option === 'ALL' ? 'All' : option[0] + option.slice(1).toLowerCase()}</button>)}</div></fieldset> }
function SuggestedOpportunities({ loading, suggestions, onAnalyze }: { loading: boolean; suggestions: { order: ExplorerOrder; score: number; dte: number }[]; onAnalyze: (order: ExplorerOrder) => void }) { const [expanded, setExpanded] = useState(false), visibleSuggestions = suggestions.slice(0, expanded ? 10 : 3); return <section className="markets-suggestions" aria-labelledby="suggested-opportunities-title"><header><div><div className="markets-suggestions-title"><span aria-hidden="true">✦</span><h2 id="suggested-opportunities-title">Suggested live opportunities</h2><small>Prototype recommendation</small></div><p>Curated picks based on your filters and current live order data.</p></div><span className="markets-why" title="Prototype recommendations rank currently loaded live OptionBook orders using simple rule-based signals such as market outlook, strike proximity, DTE and available size. They are for exploration and are not financial advice.">Why these? <b aria-hidden="true">ⓘ</b></span></header>{loading && !suggestions.length ? <div className="markets-suggestions-empty">Loading current live orders…</div> : !suggestions.length ? <div className="markets-suggestions-empty">No live opportunities match the current filters.</div> : <><div className="markets-suggestion-table-wrap"><table className="markets-suggestion-table"><thead><tr><th>Asset</th><th>Type</th><th>Strike</th><th>Expiry (DTE)</th><th>Premium</th><th>Size</th><th>Match Score</th><th>Action</th></tr></thead><tbody>{visibleSuggestions.map(({ order, score, dte }) => { const asset = orderAsset(order), type = orderType(order); return <tr key={order.id}><td><span className={`markets-row-asset ${asset.toLowerCase()}`}><i><TokenIcon asset={asset} /></i>{asset}</span></td><td><span className={`markets-type ${type.toLowerCase()}`}>{type === 'SPREAD' ? 'Spread' : type[0] + type.slice(1).toLowerCase()}</span></td><td><b>{order.strikes}</b></td><td>{formatCompactExpiry(order.expiry)} · {dte}d</td><td>{formatNumber(order.pricePerContract, 6)} <small>{order.collateral}</small></td><td>{formatNumber(order.availableAmount, 4)}</td><td><span className="markets-match-score"><b>{score}</b></span></td><td><button type="button" onClick={() => onAnalyze(order)}>Analyze <span aria-hidden="true">→</span></button></td></tr> })}</tbody></table></div>{suggestions.length > 3 && <button className="markets-view-more" type="button" onClick={() => setExpanded(value => !value)}>{expanded ? 'Show fewer opportunities' : 'View more opportunities'} <span aria-hidden="true">→</span></button>}</>}</section> }
function OrdersTable({ loading, orders, total, page, totalPages, onPage, onAnalyze }: { loading: boolean; orders: ExplorerOrder[]; total: number; page: number; totalPages: number; onPage: (page: number) => void; onAnalyze: (order: ExplorerOrder) => void }) { const start = total ? (page - 1) * PAGE_SIZE + 1 : 0, end = Math.min(page * PAGE_SIZE, total); return <section className="markets-table-panel" id="all-live-orders"><header className="markets-orders-heading"><div><h2>All live orders</h2><p>Real-time OptionBook orders across all markets.</p></div><span className="markets-live">● Live</span></header>{loading && !total ? <div className="markets-empty">Loading live OptionBook orders…</div> : !total ? <div className="markets-empty">No active orders match these filters.</div> : <><div className="markets-table-wrap"><table className="markets-table"><thead><tr><th>Asset</th><th>Type</th><th>Strike</th><th>Expiry</th><th>Premium</th><th>Available</th><th>Action</th></tr></thead><tbody>{orders.map(order => <OrderRow key={order.id} order={order} onAnalyze={onAnalyze} />)}</tbody></table></div><div className="markets-pagination"><span>Showing {start}–{end} of {total} orders</span><div><button type="button" disabled={page === 1} onClick={() => onPage(page - 1)}>‹</button>{Array.from({ length: totalPages }, (_, index) => index + 1).filter(number => number === 1 || number === totalPages || Math.abs(number - page) <= 1).map((number, index, visible) => <span key={number}>{index > 0 && visible[index - 1] !== number - 1 && <em>…</em>}<button type="button" className={number === page ? 'active' : ''} onClick={() => onPage(number)}>{number}</button></span>)}<button type="button" disabled={page === totalPages} onClick={() => onPage(page + 1)}>›</button></div></div></>}</section> }
function OrderRow({ order, onAnalyze }: { order: ExplorerOrder; onAnalyze: (order: ExplorerOrder) => void }) { const asset = orderAsset(order), type = orderType(order); return <tr onClick={() => onAnalyze(order)}><td><span className={`markets-row-asset ${asset.toLowerCase()}`}><i><TokenIcon asset={asset} /></i>{asset}</span></td><td><span className={`markets-type ${type.toLowerCase()}`}>{type === 'SPREAD' ? 'Spread' : type[0] + type.slice(1).toLowerCase()}</span></td><td>{order.strikes}</td><td>{formatCompactExpiry(order.expiry)}</td><td>{formatNumber(order.pricePerContract, 6)} <small>{order.collateral}</small></td><td>{formatNumber(order.availableAmount, 4)}</td><td><button type="button" onClick={event => { event.stopPropagation(); onAnalyze(order) }}>Analyze</button></td></tr> }
function ActivityRail({ activity, onBrowseAnalyze }: { activity: { total: number; calls: number; puts: number; spreads: number; nearestExpiry?: string; byAsset: readonly (readonly [string, number])[] }; onBrowseAnalyze: () => void }) { return <aside className="markets-activity"><section><header><h2>Market Activity</h2><span className="markets-live">● Live</span></header><ActivityRow label="Active orders" value={formatNumber(activity.total)} /><ActivityRow label="Calls" value={formatNumber(activity.calls)} /><ActivityRow label="Puts" value={formatNumber(activity.puts)} /><ActivityRow label="Spreads" value={formatNumber(activity.spreads)} /><ActivityRow label="Nearest expiry" value={activity.nearestExpiry ? formatCompactExpiry(activity.nearestExpiry) : 'Unavailable'} /></section><section><header><h2>Asset Breakdown</h2><span className="markets-rail-label">Live orders</span></header>{activity.byAsset.map(([asset, count]) => <div className="markets-breakdown" key={asset}><span className={asset.toLowerCase()}><i><TokenIcon asset={asset} /></i>{asset}</span><b>{formatNumber(count)}</b></div>)}</section><section className="markets-analyze-helper"><h2>Ready to analyze?</h2><p>Select an order to understand risk, payoff, and expiry outcomes.</p><button type="button" onClick={onBrowseAnalyze}>Learn how Analyze works <span aria-hidden="true">→</span></button></section></aside> }
function ActivityRow({ label, value }: { label: string; value: string }) { return <div className="markets-activity-row"><span>{label}</span><b>{value}</b></div> }
